package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.BugCheckerRefactoringTestHelper.TestMode;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class RefasterReturnTypeTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterReturnType.class, getClass())
        .addSourceLines(
            "A.java",
            "import static org.assertj.core.api.Assertions.assertThat;",
            "",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.AlsoNegation;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.AbstractList;",
            "import java.util.ArrayList;",
            "import java.util.LinkedList;",
            "import java.util.List;",
            "import java.util.function.Supplier;",
            "import java.util.stream.Stream;",
            "import org.assertj.core.api.AbstractAssert;",
            "",
            "class A {",
            "  class X {}",
            "",
            "  class ComplicatedReturnType {",
            "    @BeforeTemplate",
            "    AbstractAssert<?, ?> before(CharSequence charSequence) {",
            "      return Refaster.anyOf(",
            "          assertThat(charSequence.isEmpty()).isFalse(),",
            "          assertThat(charSequence.length()).isNotEqualTo(0),",
            "          assertThat(charSequence.length()).isPositive());",
            "    }",
            "  }",
            "",
            "  class XxxRenameMe {",
            "    @BeforeTemplate",
            "    // XXX: This case should not be flagged.",
            "    // BUG: Diagnostic contains:",
            "    CharSequence before() {",
            "      return (CharSequence & Comparable<?>) null;",
            "    }",
            "",
            "    @BeforeTemplate",
            "    // XXX: This case should not be flagged.",
            "    // BUG: Diagnostic contains:",
            "    Comparable<?> before2() {",
            "      return (CharSequence & Comparable<?>) null;",
            "    }",
            "  }",
            "",
            "  class NonTemplateMethod {",
            "    Object method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  class VoidReturnType {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "  }",
            "",
            "  class MatchingReturnType {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  class BroaderReturnTypeBefore {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  class BroaderReturnTypeAfter {",
            "    @AfterTemplate",
            "    // BUG: Diagnostic contains:",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class NullReturn {",
            "    @BeforeTemplate",
            "    Object before() {",
            "      return null;",
            "    }",
            "  }",
            "",
            "  class GenericTypeVariable {",
            "    @BeforeTemplate",
            "    <T> T before(T input) {",
            "      return input;",
            "    }",
            "  }",
            "",
            "  class MatchingParameterizedType {",
            "    @BeforeTemplate",
            "    ArrayList<String> before() {",
            "      return new ArrayList<String>();",
            "    }",
            "  }",
            "",
            "  class BroaderParameterizedReturnType {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    List<String> before() {",
            "      return new ArrayList<String>();",
            "    }",
            "  }",
            "",
            "  class NoReturnExpressions {",
            "    @BeforeTemplate",
            "    String before() {",
            "      throw new UnsupportedOperationException();",
            "    }",
            "  }",
            "",
            "  class MultipleReturnsSameType {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(boolean flag) {",
            "      if (flag) {",
            "        return \"a\";",
            "      }",
            "      return \"b\";",
            "    }",
            "  }",
            "",
            "  class MultipleReturnsDifferentTypes {",
            "    @BeforeTemplate",
            "    Object before(String s, boolean flag) {",
            "      if (flag) {",
            "        return s;",
            "      }",
            "      return Integer.valueOf(0);",
            "    }",
            "  }",
            "",
            "  class CapturedWildcardTypeArgument {",
            "    @BeforeTemplate",
            "    List<?> before(List<?> list) {",
            "      return list.subList(0, 1);",
            "    }",
            "  }",
            "",
            "  class ReturnInsideLambda {",
            "    @BeforeTemplate",
            "    Supplier<String> before() {",
            "      Supplier<String> s =",
            "          () -> {",
            "            return \"\";",
            "          };",
            "      return s;",
            "    }",
            "  }",
            "",
            "  class BroaderReturnTypeForVoid {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(Void v) {",
            "      return v;",
            "    }",
            "  }",
            "",
            "  class BroaderParameterizedReturnTypeForVoid {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    List<?> before(List<Void> list) {",
            "      return list;",
            "    }",
            "  }",
            "",
            "  class BroaderParameterizedReturnTypeForNestedVoid {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    List<?> before(List<List<Void>> list) {",
            "      return list;",
            "    }",
            "  }",
            "",
            "  class AlsoNegationMatchingPrimitive {",
            "    @BeforeTemplate",
            "    boolean before(boolean a, boolean b) {",
            "      return Refaster.anyOf(",
            "          Stream.of(a).reduce(b, Boolean::logicalOr), Stream.of(a).reduce(b, Boolean::logicalAnd));",
            "    }",
            "",
            "    @AfterTemplate",
            "    @AlsoNegation",
            "    boolean after(boolean a, boolean b) {",
            "      return a || b;",
            "    }",
            "  }",
            "",
            "  class CompoundTypeNarrowable {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(ArrayList<String> list, LinkedList<String> linked) {",
            "      return Refaster.anyOf(list, linked);",
            "    }",
            "  }",
            "",
            "  class CompoundTypeMatching {",
            "    @BeforeTemplate",
            "    AbstractList<String> before(ArrayList<String> list, LinkedList<String> linked) {",
            "      return Refaster.anyOf(list, linked);",
            "    }",
            "  }",
            "",
            "  class CapturedTypeArgNarrowable {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(List<?> list) {",
            "      return list.subList(0, 1);",
            "    }",
            "  }",
            "",
            "  class AlsoNegationBroaderReturnType {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(boolean a, boolean b) {",
            "      return Refaster.anyOf(",
            "          Stream.of(a).reduce(b, Boolean::logicalOr), Stream.of(a).reduce(b, Boolean::logicalAnd));",
            "    }",
            "",
            "    @AfterTemplate",
            "    @AlsoNegation",
            "    // BUG: Diagnostic contains:",
            "    Object after(boolean a, boolean b) {",
            "      return a || b;",
            "    }",
            "  }",
            "",
            "  class AlsoNegationNonBooleanReturnType {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(String s) {",
            "      return s.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    @AlsoNegation",
            "    // BUG: Diagnostic contains:",
            "    Object after(String s) {",
            "      return s.strip();",
            "    }",
            "  }",
            "",
            "  class BoundedCapturedWildcardTypeArgument {",
            "    @BeforeTemplate",
            "    List<? extends Number> before(List<? extends Number> list) {",
            "      return list.subList(0, 1);",
            "    }",
            "  }",
            "",
            "  class BoundedCapturedWildcardTypeArgumentNarrowable {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(List<? extends Number> list) {",
            "      return list.subList(0, 1);",
            "    }",
            "  }",
            "",
            "  class AnonymousClassExtendsConcreteNarrowable {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before() {",
            "      return new ArrayList<String>() {};",
            "    }",
            "  }",
            "",
            "  class AnonymousClassExtendsConcreteMatching {",
            "    @BeforeTemplate",
            "    ArrayList<String> before() {",
            "      return new ArrayList<String>() {};",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterReturnType.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  @BeforeTemplate",
            "  Object before(String str) {",
            "    return str.trim();",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  @BeforeTemplate",
            "  String before(String str) {",
            "    return str.trim();",
            "  }",
            "}")
        .addInputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "",
            "class B {",
            "  @AfterTemplate",
            "  CharSequence after(String str) {",
            "    return str.strip();",
            "  }",
            "}")
        .addOutputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "",
            "class B {",
            "  @AfterTemplate",
            "  String after(String str) {",
            "    return str.strip();",
            "  }",
            "}")
        .addInputLines(
            "C.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class C {",
            "  @BeforeTemplate",
            "  Object before(Void v) {",
            "    return v;",
            "  }",
            "}")
        .addOutputLines(
            "C.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import org.jspecify.annotations.Nullable;",
            "",
            "class C {",
            "  @BeforeTemplate",
            "  @Nullable Void before(Void v) {",
            "    return v;",
            "  }",
            "}")
        .addInputLines(
            "D.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "",
            "class D {",
            "  @BeforeTemplate",
            "  List<?> before(List<Void> list) {",
            "    return list;",
            "  }",
            "}")
        .addOutputLines(
            "D.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "import org.jspecify.annotations.Nullable;",
            "",
            "class D {",
            "  @BeforeTemplate",
            "  List<? extends @Nullable Void> before(List<Void> list) {",
            "    return list;",
            "  }",
            "}")
        .addInputLines(
            "E.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "import java.util.List;",
            "",
            "class E {",
            "  @BeforeTemplate",
            "  List<String> before() {",
            "    return new ArrayList<String>();",
            "  }",
            "}")
        .addOutputLines(
            "E.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "import java.util.List;",
            "",
            "class E {",
            "  @BeforeTemplate",
            "  ArrayList<String> before() {",
            "    return new ArrayList<String>();",
            "  }",
            "}")
        .addInputLines(
            "F.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "",
            "class F {",
            "  @BeforeTemplate",
            "  List<?> before(List<List<Void>> list) {",
            "    return list;",
            "  }",
            "}")
        .addOutputLines(
            "F.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "import org.jspecify.annotations.Nullable;",
            "",
            "class F {",
            "  @BeforeTemplate",
            "  List<List<@Nullable Void>> before(List<List<Void>> list) {",
            "    return list;",
            "  }",
            "}")
        .addInputLines(
            "G.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.AlsoNegation;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.stream.Stream;",
            "",
            "class G {",
            "  @BeforeTemplate",
            "  Object before(boolean a, boolean b) {",
            "    return Refaster.anyOf(",
            "        Stream.of(a).reduce(b, Boolean::logicalOr), Stream.of(a).reduce(b, Boolean::logicalAnd));",
            "  }",
            "",
            "  @AfterTemplate",
            "  @AlsoNegation",
            "  Object after(boolean a, boolean b) {",
            "    return a || b;",
            "  }",
            "}")
        .addOutputLines(
            "G.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.AlsoNegation;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.stream.Stream;",
            "",
            "class G {",
            "  @BeforeTemplate",
            "  boolean before(boolean a, boolean b) {",
            "    return Refaster.anyOf(",
            "        Stream.of(a).reduce(b, Boolean::logicalOr), Stream.of(a).reduce(b, Boolean::logicalAnd));",
            "  }",
            "",
            "  @AfterTemplate",
            "  @AlsoNegation",
            "  boolean after(boolean a, boolean b) {",
            "    return a || b;",
            "  }",
            "}")
        .addInputLines(
            "H.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "import java.util.LinkedList;",
            "",
            "class H {",
            "  @BeforeTemplate",
            "  Object before(ArrayList<String> list, LinkedList<String> linked) {",
            "    return Refaster.anyOf(list, linked);",
            "  }",
            "}")
        .addOutputLines(
            "H.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.AbstractList;",
            "import java.util.ArrayList;",
            "import java.util.LinkedList;",
            "",
            "class H {",
            "  @BeforeTemplate",
            "  AbstractList<String> before(ArrayList<String> list, LinkedList<String> linked) {",
            "    return Refaster.anyOf(list, linked);",
            "  }",
            "}")
        .addInputLines(
            "I.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "",
            "class I {",
            "  @BeforeTemplate",
            "  Object before(List<?> list) {",
            "    return list.subList(0, 1);",
            "  }",
            "}")
        .addOutputLines(
            "I.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "",
            "class I {",
            "  @BeforeTemplate",
            "  List<?> before(List<?> list) {",
            "    return list.subList(0, 1);",
            "  }",
            "}")
        .addInputLines(
            "J.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.AlsoNegation;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class J {",
            "  @BeforeTemplate",
            "  Object before(String s) {",
            "    return s.trim();",
            "  }",
            "",
            "  @AfterTemplate",
            "  @AlsoNegation",
            "  Object after(String s) {",
            "    return s.strip();",
            "  }",
            "}")
        .addOutputLines(
            "J.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.AlsoNegation;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class J {",
            "  @BeforeTemplate",
            "  String before(String s) {",
            "    return s.trim();",
            "  }",
            "",
            "  @AfterTemplate",
            "  @AlsoNegation",
            "  String after(String s) {",
            "    return s.strip();",
            "  }",
            "}")
        .addInputLines(
            "L.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "",
            "class L {",
            "  @BeforeTemplate",
            "  Object before() {",
            "    return new ArrayList<String>() {};",
            "  }",
            "}")
        .addOutputLines(
            "L.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "",
            "class L {",
            "  @BeforeTemplate",
            "  ArrayList<String> before() {",
            "    return new ArrayList<String>() {};",
            "  }",
            "}")
        .addInputLines(
            "K.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "",
            "class K {",
            "  @BeforeTemplate",
            "  Object before(List<? extends Number> list) {",
            "    return list.subList(0, 1);",
            "  }",
            "}")
        .addOutputLines(
            "K.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "",
            "class K {",
            "  @BeforeTemplate",
            "  List<? extends Number> before(List<? extends Number> list) {",
            "    return list.subList(0, 1);",
            "  }",
            "}")
        .doTest(TestMode.TEXT_MATCH);
  }
}
