package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.BugCheckerRefactoringTestHelper.TestMode;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class RefasterReturnTypeTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterReturnType.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "import java.util.List;",
            "import java.util.function.Supplier;",
            "",
            "class A {",
            "  class NonTemplateMethod {",
            "    Object method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  class VoidReturnType {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "  }",
            "",
            "  class MatchingReturnType {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  class BroaderReturnTypeBefore {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  class BroaderReturnTypeAfter {",
            "    @AfterTemplate",
            "    // BUG: Diagnostic contains:",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class NullReturn {",
            "    @BeforeTemplate",
            "    Object before() {",
            "      return null;",
            "    }",
            "  }",
            "",
            "  class GenericTypeVariable {",
            "    @BeforeTemplate",
            "    <T> T before(T input) {",
            "      return input;",
            "    }",
            "  }",
            "",
            "  class MatchingParameterizedType {",
            "    @BeforeTemplate",
            "    ArrayList<String> before() {",
            "      return new ArrayList<String>();",
            "    }",
            "  }",
            "",
            "  class BroaderParameterizedReturnType {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    List<String> before() {",
            "      return new ArrayList<String>();",
            "    }",
            "  }",
            "",
            "  class NoReturnExpressions {",
            "    @BeforeTemplate",
            "    String before() {",
            "      throw new UnsupportedOperationException();",
            "    }",
            "  }",
            "",
            "  class MultipleReturnsSameType {",
            "    @BeforeTemplate",
            "    // BUG: Diagnostic contains:",
            "    Object before(boolean flag) {",
            "      if (flag) {",
            "        return \"a\";",
            "      }",
            "      return \"b\";",
            "    }",
            "  }",
            "",
            "  class MultipleReturnsDifferentTypes {",
            "    @BeforeTemplate",
            "    Object before(String s, boolean flag) {",
            "      if (flag) {",
            "        return s;",
            "      }",
            "      return Integer.valueOf(0);",
            "    }",
            "  }",
            "",
            "  class ReturnInsideLambda {",
            "    @BeforeTemplate",
            "    Supplier<String> before() {",
            "      Supplier<String> s =",
            "          () -> {",
            "            return \"\";",
            "          };",
            "      return s;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterReturnType.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  @BeforeTemplate",
            "  Object before(String str) {",
            "    return str.trim();",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  @BeforeTemplate",
            "  String before(String str) {",
            "    return str.trim();",
            "  }",
            "}")
        .addInputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "",
            "class B {",
            "  @AfterTemplate",
            "  CharSequence after(String str) {",
            "    return str.strip();",
            "  }",
            "}")
        .addOutputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "",
            "class B {",
            "  @AfterTemplate",
            "  String after(String str) {",
            "    return str.strip();",
            "  }",
            "}")
        .doTest(TestMode.TEXT_MATCH);
  }
}
