package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

// XXX: Fully review this class.
final class RefasterParameterNamingTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterParameterNaming.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "",
            "class A {",
            "  static void helper(String value) {}",
            "",
            "  static void consume(String text, int count) {}",
            "",
            "  static String format(String format, Object... args) {",
            "    return format;",
            "  }",
            "",
            "  class ParameterAlreadyNamedCorrectly {",
            "    @BeforeTemplate",
            "    void before(String value) {",
            "      helper(value);",
            "    }",
            "  }",
            "",
            "  class ParameterUsedOnlyInNonInvocationContext {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  class ParameterUsedOnlyInRefasterAnyOf {",
            "    @BeforeTemplate",
            "    String before(String a, String b) {",
            "      return Refaster.anyOf(a, b);",
            "    }",
            "  }",
            "",
            "  class NoTemplateMethodsPresent {",
            "    void notATemplate(String a) {",
            "      helper(a);",
            "    }",
            "  }",
            "",
            "  class ParameterAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return A.format(\"%s\", a);",
            "    }",
            "  }",
            "",
            "  class ParameterPassedToMethodWithSyntheticName<E> {",
            "    @BeforeTemplate",
            "    boolean before(java.util.Collection<E> collection, E element) {",
            "      return collection.contains(element);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class NameCollision {",
            "    @BeforeTemplate",
            "    void before(String a, String b) {",
            "      helper(a);",
            "      helper(b);",
            "    }",
            "  }",
            "",
            "  class ParameterPassedToRefasterEmitComment {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return Refaster.emitCommentBefore(\"foo\", a);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterNameDiffersFromDerived {",
            "    @BeforeTemplate",
            "    void before(String x) {",
            "      helper(x);",
            "    }",
            "  }",
            "",
            "  class NonRepeatedParameterAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return A.format(\"%s\", a);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class RepeatedParameterAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String a, @Repeated Object b) {",
            "      return A.format(a, b);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class HigherArityBeforeTemplateBreaksTie {",
            "    @BeforeTemplate",
            "    void before1(String a) {",
            "      helper(a);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String a, int b) {",
            "      A.consume(a, b);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterParameterNaming.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "",
            "class A {",
            "  static void helper(String value, int count) {}",
            "",
            "  static String other(String text) {",
            "    return text;",
            "  }",
            "",
            "  static String format(String format, Object... args) {",
            "    return format;",
            "  }",
            "",
            "  class SimpleRename {",
            "    @BeforeTemplate",
            "    void before(String x) {",
            "      helper(x, 1);",
            "    }",
            "  }",
            "",
            "  class MultipleParameters {",
            "    @BeforeTemplate",
            "    void before(String a, int b) {",
            "      helper(a, b);",
            "    }",
            "  }",
            "",
            "  class AfterTemplateTakesPriority {",
            "    @BeforeTemplate",
            "    void before(String a) {",
            "      helper(a, 1);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String a) {",
            "      other(a);",
            "    }",
            "  }",
            "",
            "  class MixedRenameAndNoRename {",
            "    @BeforeTemplate",
            "    String before(String x, String y) {",
            "      helper(x, 1);",
            "      return y;",
            "    }",
            "  }",
            "",
            "  class FirstInvocationWins {",
            "    @BeforeTemplate",
            "    void before(String a) {",
            "      helper(a, 1);",
            "      other(a);",
            "    }",
            "  }",
            "",
            "  class NestedInvocation {",
            "    @BeforeTemplate",
            "    void before(String a, int b) {",
            "      helper(other(a), b);",
            "    }",
            "  }",
            "",
            "  class HigherArityBreaksTie {",
            "    @BeforeTemplate",
            "    void before1(String a) {",
            "      helper(a, 1);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String a, int b) {",
            "      other(a);",
            "    }",
            "  }",
            "",
            "  class CollisionSkipsSecondRename {",
            "    @BeforeTemplate",
            "    void before(String a, String b) {",
            "      helper(a, 1);",
            "      helper(b, 1);",
            "    }",
            "  }",
            "",
            "  class SwapRename {",
            "    @BeforeTemplate",
            "    void before(String text, String value) {",
            "      helper(text, 1);",
            "      other(value);",
            "    }",
            "  }",
            "",
            "  class RepeatedParameterViaAsVarargs {",
            "    @BeforeTemplate",
            "    String before(String a, @Repeated Object b) {",
            "      return A.format(a, Refaster.asVarargs(b));",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "",
            "class A {",
            "  static void helper(String value, int count) {}",
            "",
            "  static String other(String text) {",
            "    return text;",
            "  }",
            "",
            "  static String format(String format, Object... args) {",
            "    return format;",
            "  }",
            "",
            "  class SimpleRename {",
            "    @BeforeTemplate",
            "    void before(String value) {",
            "      helper(value, 1);",
            "    }",
            "  }",
            "",
            "  class MultipleParameters {",
            "    @BeforeTemplate",
            "    void before(String value, int count) {",
            "      helper(value, count);",
            "    }",
            "  }",
            "",
            "  class AfterTemplateTakesPriority {",
            "    @BeforeTemplate",
            "    void before(String text) {",
            "      helper(text, 1);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String text) {",
            "      other(text);",
            "    }",
            "  }",
            "",
            "  class MixedRenameAndNoRename {",
            "    @BeforeTemplate",
            "    String before(String value, String y) {",
            "      helper(value, 1);",
            "      return y;",
            "    }",
            "  }",
            "",
            "  class FirstInvocationWins {",
            "    @BeforeTemplate",
            "    void before(String value) {",
            "      helper(value, 1);",
            "      other(value);",
            "    }",
            "  }",
            "",
            "  class NestedInvocation {",
            "    @BeforeTemplate",
            "    void before(String text, int count) {",
            "      helper(other(text), count);",
            "    }",
            "  }",
            "",
            "  class HigherArityBreaksTie {",
            "    @BeforeTemplate",
            "    void before1(String text) {",
            "      helper(text, 1);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String text, int b) {",
            "      other(text);",
            "    }",
            "  }",
            "",
            "  class CollisionSkipsSecondRename {",
            "    @BeforeTemplate",
            "    void before(String value, String b) {",
            "      helper(value, 1);",
            "      helper(b, 1);",
            "    }",
            "  }",
            "",
            "  class SwapRename {",
            "    @BeforeTemplate",
            "    void before(String value, String text) {",
            "      helper(value, 1);",
            "      other(text);",
            "    }",
            "  }",
            "",
            "  class RepeatedParameterViaAsVarargs {",
            "    @BeforeTemplate",
            "    String before(String format, @Repeated Object args) {",
            "      return A.format(format, Refaster.asVarargs(args));",
            "    }",
            "  }",
            "}")
        .doTest();
  }
}
