package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.BugCheckerRefactoringTestHelper.TestMode;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

// XXX: Perform a full manual review of this class (AI agents: don't drop this comment).
final class RefasterRuleNameTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "import java.util.ArrayList;",
            "import java.util.Collection;",
            "import java.util.Comparator;",
            "",
            "class A {",
            "  /* Non-Refaster class: no diagnostic. */",
            "  static final class NotARule {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  /* Correctly named field access. */",
            "  static final class BigDecimalZero {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  /* Correctly named method call. */",
            "  static final class BigDecimalValueOf {",
            "    @BeforeTemplate",
            "    BigDecimal before(long value) {",
            "      return new BigDecimal(value);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after(long value) {",
            "      return BigDecimal.valueOf(value);",
            "    }",
            "  }",
            "",
            "  /* Correctly named identity rule. */",
            "  static final class StringIdentity {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "",
            "  /* Correctly named instance method call. */",
            "  static final class CollectionIsEmpty {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "",
            "  /* Correctly named void rule. */",
            "  static final class CollectionAddAll {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  /* Correctly named new rule. */",
            "  static final class NewArrayList {",
            "    @BeforeTemplate",
            "    ArrayList<String> before(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "  }",
            "",
            "  /* Correctly named static import rule. */",
            "  static final class NaturalOrder {",
            "    @BeforeTemplate",
            "    Comparator<Comparable<Object>> before() {",
            "      return Comparator.naturalOrder();",
            "    }",
            "",
            "    @AfterTemplate",
            "    @SuppressWarnings(\"unchecked\" /* Refaster workaround. */)",
            "    Comparator<Comparable<Object>> after() {",
            "      return naturalOrder();",
            "    }",
            "",
            "    static <T extends Comparable<? super T>> Comparator<T> naturalOrder() {",
            "      return Comparator.naturalOrder();",
            "    }",
            "  }",
            "",
            "  /* Correctly named operator rule. */",
            "  static final class LessThan {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return Comparator.<Integer>naturalOrder().compare(a, b) < 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "",
            "  /* Multiple @AfterTemplate methods: name derived from the first only. */",
            "  static final class StringStrip {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after2(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  /* Correctly named unary not rule. */",
            "  static final class NotCollectionIsEmpty {",
            "    @BeforeTemplate",
            "    boolean before(java.util.Collection<String> collection) {",
            "      return collection.size() != 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(java.util.Collection<String> collection) {",
            "      return !collection.isEmpty();",
            "    }",
            "  }",
            "",
            "  /* Correctly named void method call with non-parameter argument. */",
            "  static final class CollectionAdd {",
            "    @BeforeTemplate",
            "    void before(java.util.Collection<String> addTo, String elem) {",
            "      addTo.contains(elem);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(java.util.Collection<String> addTo, String elem) {",
            "      addTo.add(elem);",
            "    }",
            "  }",
            "",
            "  /* Correctly named instanceof rule. */",
            "  static final class InstanceofString {",
            "    @BeforeTemplate",
            "    boolean before(Object o) {",
            "      return o.getClass() == String.class;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Object o) {",
            "      return o instanceof String;",
            "    }",
            "  }",
            "",
            "  /* Type cast and parenthesized: cast is transparent, expression is traversed. */",
            "  static final class StringLength {",
            "    @BeforeTemplate",
            "    int before(String str) {",
            "      return str.toCharArray().length;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(String str) {",
            "      return (int) (str.length());",
            "    }",
            "  }",
            "",
            "  /* Correctly named conditional expression rule. */",
            "  static final class StringIsEmptyTrueNull {",
            "    @BeforeTemplate",
            "    Boolean before(String str) {",
            "      return str.length() == 0 ? Boolean.TRUE : null;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Boolean after(String str) {",
            "      return str.isEmpty() ? true : null;",
            "    }",
            "  }",
            "",
            "  /* Correctly named boolean literal rule. */",
            "  static final class True {",
            "    @BeforeTemplate",
            "    boolean before() {",
            "      return false;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after() {",
            "      return true;",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class B {",
            "  /* Correctly disambiguated Expression/Block pair. */",
            "  static final class CollectionAddAllExpression {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.containsAll(elementsToAdd);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddAllBlock {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "C.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "import java.math.BigDecimal;",
            "import java.util.Arrays;",
            "import java.util.Collections;",
            "import java.util.Comparator;",
            "import java.util.stream.Stream;",
            "",
            "class C {",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongName {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  /* Refaster.anyOf: wrapper is transparent. */",
            "  static final class StringValueOf {",
            "    @BeforeTemplate",
            "    String before(Object obj) {",
            "      return Refaster.anyOf(obj.toString(), \"\" + obj);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Object obj) {",
            "      return String.valueOf(obj);",
            "    }",
            "  }",
            "",
            "  /* Refaster.asVarargs: wrapper is transparent. */",
            "  static final class CollectionsMinArraysAsList {",
            "    @BeforeTemplate",
            "    String before(@Repeated String value, Comparator<String> cmp) {",
            "      return Stream.of(Refaster.asVarargs(value)).min(cmp).orElseThrow();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(@Repeated String value, Comparator<String> cmp) {",
            "      return Collections.min(Arrays.asList(Refaster.asVarargs(value)), cmp);",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "PlaceholderRules.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Placeholder;",
            "import java.util.stream.Collector;",
            "import java.util.stream.Stream;",
            "",
            "class PlaceholderRules {",
            "  /* Rule with @Placeholder: placeholder invocations are skipped in naming. */",
            "  abstract static class StreamCollect<E, R> {",
            "    @Placeholder",
            "    abstract Collector<E, ?, R> collector();",
            "",
            "    @BeforeTemplate",
            "    R before(Stream<E> stream) {",
            "      return stream.collect(collector());",
            "    }",
            "",
            "    @AfterTemplate",
            "    R after(Stream<E> stream) {",
            "      return stream.collect(collector());",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "D.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class D {",
            "  // BUG: Diagnostic contains:",
            "  static final class Wrong {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "E.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Comparator;",
            "",
            "class E {",
            "  // BUG: Diagnostic contains:",
            "  static final class Bad {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return Comparator.<Integer>naturalOrder().compare(a, b) < 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "",
            "class A {",
            "  static final class WrongName {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "",
            "class A {",
            "  static final class BigDecimalZero {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class B {",
            "  static final class Wrong {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class B {",
            "  static final class StringIdentity {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "C.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class C {",
            "  static final class BadName {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "C.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class C {",
            "  static final class CollectionIsEmpty {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "D.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class D {",
            "  static final class Bad {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return a >= b;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "D.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class D {",
            "  static final class LessThan {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return a >= b;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "E.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "import java.util.Collection;",
            "",
            "class E {",
            "  static final class Bad {",
            "    @BeforeTemplate",
            "    ArrayList<String> before(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "E.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "import java.util.Collection;",
            "",
            "class E {",
            "  static final class NewArrayList {",
            "    @BeforeTemplate",
            "    ArrayList<String> before(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "F.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "",
            "class F {",
            "  static final class BadName {",
            "    @BeforeTemplate",
            "    boolean before(BigDecimal value) {",
            "      return value.compareTo(BigDecimal.ZERO) == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(BigDecimal value) {",
            "      return value.signum() == 0;",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "F.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "",
            "class F {",
            "  static final class BigDecimalSignumEqualToZero {",
            "    @BeforeTemplate",
            "    boolean before(BigDecimal value) {",
            "      return value.compareTo(BigDecimal.ZERO) == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(BigDecimal value) {",
            "      return value.signum() == 0;",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "G.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "",
            "class G {",
            "  static final class BigDecimalZero {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  static final class BadName {",
            "    @BeforeTemplate",
            "    BigDecimal before(long value) {",
            "      return new BigDecimal(value);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after(long value) {",
            "      return BigDecimal.valueOf(value);",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "G.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "",
            "class G {",
            "  static final class BigDecimalZero {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  static final class BigDecimalValueOf {",
            "    @BeforeTemplate",
            "    BigDecimal before(long value) {",
            "      return new BigDecimal(value);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after(long value) {",
            "      return BigDecimal.valueOf(value);",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "H.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class H {",
            "  static final class Bad1 {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.containsAll(elementsToAdd);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class Bad2 {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "H.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class H {",
            "  static final class CollectionAddAllExpression {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.containsAll(elementsToAdd);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddAllBlock {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "I.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class I {",
            "  static final class Bad {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      for (String e : elementsToAdd) {",
            "        addTo.add(e);",
            "      }",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "      addTo.clear();",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "I.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class I {",
            "  static final class CollectionAddAllCollectionClear {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      for (String e : elementsToAdd) {",
            "        addTo.add(e);",
            "      }",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "      addTo.clear();",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "J.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "import java.util.Comparator;",
            "",
            "class J {",
            "  static final class Bad1 {",
            "    @BeforeTemplate",
            "    String before(Collection<String> collection) {",
            "      return collection.stream().findFirst().orElseThrow();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Collection<String> collection) {",
            "      return collection.iterator().next();",
            "    }",
            "  }",
            "",
            "  static final class Bad2 {",
            "    @BeforeTemplate",
            "    String before(Collection<String> collection, Comparator<String> cmp) {",
            "      return collection.stream().min(cmp).orElseThrow();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Collection<String> collection, Comparator<String> cmp) {",
            "      return collection.iterator().next();",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "J.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "import java.util.Comparator;",
            "",
            "class J {",
            "  static final class CollectionIteratorNext {",
            "    @BeforeTemplate",
            "    String before(Collection<String> collection) {",
            "      return collection.stream().findFirst().orElseThrow();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Collection<String> collection) {",
            "      return collection.iterator().next();",
            "    }",
            "  }",
            "",
            "  static final class CollectionIteratorNextWithComparator {",
            "    @BeforeTemplate",
            "    String before(Collection<String> collection, Comparator<String> cmp) {",
            "      return collection.stream().min(cmp).orElseThrow();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Collection<String> collection, Comparator<String> cmp) {",
            "      return collection.iterator().next();",
            "    }",
            "  }",
            "}")
        .doTest(TestMode.TEXT_MATCH);
  }

  @Test
  void identificationSameArityTypeDisambiguation() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Same arity, different types at position 0. */",
            "  static final class MathClampInt {",
            "    @BeforeTemplate",
            "    int before(int value, int min, int max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int value, int min, int max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class MathClampLong {",
            "    @BeforeTemplate",
            "    long before(long value, long min, long max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(long value, long min, long max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationRepeatedDisambiguation() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "import java.util.List;",
            "",
            "class A {",
            "  /* Same arity, one @Repeated. */",
            "  static final class ListOf {",
            "    @BeforeTemplate",
            "    <T> List<T> before(T value) {",
            "      return java.util.Collections.singletonList(value);",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> List<T> after(T value) {",
            "      return List.of(value);",
            "    }",
            "  }",
            "",
            "  static final class ListOfVarargs {",
            "    @BeforeTemplate",
            "    <T> List<T> before(@Repeated T value) {",
            "      return java.util.Arrays.asList(Refaster.asVarargs(value));",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> List<T> after(@Repeated T value) {",
            "      return List.of(Refaster.asVarargs(value));",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationReturnTypeDisambiguation() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Arrays;",
            "import java.util.Comparator;",
            "",
            "class A {",
            "  /* Zero params, return type argument differs. */",
            "  static final class ArraysCompareUnsignedByte {",
            "    @BeforeTemplate",
            "    Comparator<byte[]> before() {",
            "      return (a, b) -> 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Comparator<byte[]> after() {",
            "      return Arrays::compareUnsigned;",
            "    }",
            "  }",
            "",
            "  static final class ArraysCompareUnsignedInt {",
            "    @BeforeTemplate",
            "    Comparator<int[]> before() {",
            "      return (a, b) -> 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Comparator<int[]> after() {",
            "      return Arrays::compareUnsigned;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationMixedArityWithSameAritySubgroups() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Mixed arity: base (0 params) + two at arity 1 with different types. */",
            "  static final class SystemGc {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithString {",
            "    @BeforeTemplate",
            "    void before(String message) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String message) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithThrowable {",
            "    @BeforeTemplate",
            "    void before(Throwable cause) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Throwable cause) {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacementSameArityTypeDisambiguation() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class Wrong1 {",
            "    @BeforeTemplate",
            "    int before(int value, int min, int max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int value, int min, int max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class Wrong2 {",
            "    @BeforeTemplate",
            "    long before(long value, long min, long max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(long value, long min, long max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class MathClampInt {",
            "    @BeforeTemplate",
            "    int before(int value, int min, int max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int value, int min, int max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class MathClampLong {",
            "    @BeforeTemplate",
            "    long before(long value, long min, long max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(long value, long min, long max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "}")
        .doTest(TestMode.TEXT_MATCH);
  }

  @Test
  void replacementMixedArityWithParameterTypes() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class Bad1 {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class Bad2 {",
            "    @BeforeTemplate",
            "    void before(String message) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String message) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class Bad3 {",
            "    @BeforeTemplate",
            "    void before(Throwable cause) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Throwable cause) {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class SystemGc {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithString {",
            "    @BeforeTemplate",
            "    void before(String message) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String message) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithThrowable {",
            "    @BeforeTemplate",
            "    void before(Throwable cause) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Throwable cause) {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .doTest(TestMode.TEXT_MATCH);
  }

  @Test
  void identificationMultiPositionTypeDisambiguation() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* 4 rules: no single position has all-unique types, but {0,1} does. */",
            "  static final class SystemGcIntString {",
            "    @BeforeTemplate",
            "    void before(int a, String b) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, String b) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcIntThrowable {",
            "    @BeforeTemplate",
            "    void before(int a, Throwable b) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, Throwable b) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcLongString {",
            "    @BeforeTemplate",
            "    void before(long a, String b) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(long a, String b) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcLongThrowable {",
            "    @BeforeTemplate",
            "    void before(long a, Throwable b) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(long a, Throwable b) {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationSuffixComposition() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Mixed arity {2,3,2,3}, type at pos 1 differs (int vs String). */",
            "  static final class SystemGcInt {",
            "    @BeforeTemplate",
            "    void before(int a, int b) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, int b) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcString {",
            "    @BeforeTemplate",
            "    void before(int a, String b) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, String b) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcIntWithInt {",
            "    @BeforeTemplate",
            "    void before(int a, int b, int c) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, int b, int c) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcStringWithInt {",
            "    @BeforeTemplate",
            "    void before(int a, String b, int c) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, String b, int c) {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationExpressionBlockInSubClash() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Objects;",
            "",
            "class A {",
            "  /* Mixed arity {1,1,2,2}, each pair has void/non-void. */",
            "  static final class ObjectsRequireNonNullExpression {",
            "    @BeforeTemplate",
            "    <T> T before(T obj) {",
            "      return obj;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> T after(T obj) {",
            "      return Objects.requireNonNull(obj);",
            "    }",
            "  }",
            "",
            "  static final class ObjectsRequireNonNullBlock {",
            "    @BeforeTemplate",
            "    <T> void before(T obj) {",
            "      if (obj == null) throw new NullPointerException();",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> void after(T obj) {",
            "      Objects.requireNonNull(obj);",
            "    }",
            "  }",
            "",
            "  static final class ObjectsRequireNonNullWithStringExpression {",
            "    @BeforeTemplate",
            "    <T> T before(T obj, String msg) {",
            "      return obj;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> T after(T obj, String msg) {",
            "      return Objects.requireNonNull(obj, msg);",
            "    }",
            "  }",
            "",
            "  static final class ObjectsRequireNonNullWithStringBlock {",
            "    @BeforeTemplate",
            "    <T> void before(T obj, String msg) {",
            "      if (obj == null) throw new NullPointerException(msg);",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> void after(T obj, String msg) {",
            "      Objects.requireNonNull(obj, msg);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationRefasterClazz() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class ClassIsInstance {",
            "    @BeforeTemplate",
            "    <T> boolean before(Object obj) {",
            "      return obj instanceof String;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> boolean after(Object obj) {",
            "      return Refaster.<T>clazz().isInstance(obj);",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "B.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class B {",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongClazzName {",
            "    @BeforeTemplate",
            "    <T> boolean before(Object obj) {",
            "      return obj instanceof String;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> boolean after(Object obj) {",
            "      return Refaster.<T>clazz().isInstance(obj);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationManualDisambiguation() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Two rules with identical @AfterTemplate: no strategy can disambiguate. */",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name",
            "  static final class Bad1 {",
            "    @BeforeTemplate",
            "    String before(String s) {",
            "      return s.toLowerCase();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String s) {",
            "      return s.toUpperCase();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name",
            "  static final class Bad2 {",
            "    @BeforeTemplate",
            "    String before(String s) {",
            "      return s.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String s) {",
            "      return s.toUpperCase();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationArityNumberingWithRepeatedTypes() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Arity numbering kicks in when extra-param types repeat. */",
            "  static final class SystemGc1 {",
            "    @BeforeTemplate",
            "    void before(String a) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String a) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGc3 {",
            "    @BeforeTemplate",
            "    void before(String a, String b, String c) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String a, String b, String c) {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationTypeArgument() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collections;",
            "import java.util.List;",
            "",
            "class A {",
            "  /* Identical params but one has explicit type argument. */",
            "  static final class CollectionsEmptyList {",
            "    @BeforeTemplate",
            "    List<Object> before() {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<Object> after() {",
            "      return Collections.emptyList();",
            "    }",
            "  }",
            "",
            "  static final class CollectionsEmptyListObject {",
            "    @BeforeTemplate",
            "    List<Object> before() {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<Object> after() {",
            "      return Collections.<Object>emptyList();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationSuppressedRule() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  @SuppressWarnings(\"RefasterRuleName\")",
            "  static final class WrongName {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationManualDisambiguationFallback() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name 'SystemGc'",
            "  static final class SystemGc1 {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Thread.yield();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name 'SystemGc'",
            "  static final class SystemGc2 {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Thread.onSpinWait();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  /* Suppressed: no diagnostic even in manual disambiguation. */",
            "  @SuppressWarnings(\"RefasterRuleName\")",
            "  static final class SystemGc3 {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationLambdaInAfterTemplate() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.function.Predicate;",
            "",
            "class A {",
            "  static final class StringIsEmpty {",
            "    @BeforeTemplate",
            "    Predicate<String> before() {",
            "      return s -> s.length() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Predicate<String> after() {",
            "      return s -> s.isEmpty();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationLiterals() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Null literal: correctly named. */",
            "  static final class Null {",
            "    @BeforeTemplate",
            "    String before() {",
            "      return \"\";",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after() {",
            "      return null;",
            "    }",
            "  }",
            "",
            "  /* Known literal (1) as method argument. */",
            "  static final class StringSubstringOne {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.substring(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.substring(1);",
            "    }",
            "  }",
            "",
            "  /* Unknown numeric literal as method argument. */",
            "  static final class StringSubstring42 {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.substring(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.substring(42);",
            "    }",
            "  }",
            "",
            "  /* Char literal as method argument (not Number, not in LITERAL_NAMES). */",
            "  static final class StringValueOf {",
            "    @BeforeTemplate",
            "    String before() {",
            "      return \"x\";",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after() {",
            "      return String.valueOf('x');",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class B {",
            "  /* Misnamed null literal: exercises null-literal detection. */",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongNullName {",
            "    @BeforeTemplate",
            "    String before() {",
            "      return \"\";",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after() {",
            "      return null;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationRawReturnTypeDisambiguation() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class NumberIntValueInt {",
            "    @BeforeTemplate",
            "    int before(Number n) {",
            "      return (int) n.doubleValue();",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(Number n) {",
            "      return n.intValue();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class Wrong {",
            "    @BeforeTemplate",
            "    long before(Number n) {",
            "      return (long) n.doubleValue();",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(Number n) {",
            "      return n.intValue();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationMultiStatementWithReturn() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class A {",
            "  static final class CollectionAddReturnCollectionSize {",
            "    @BeforeTemplate",
            "    int before(Collection<String> c, String elem) {",
            "      c.contains(elem);",
            "      return c.size();",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(Collection<String> c, String elem) {",
            "      c.add(elem);",
            "      return c.size();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationScreamingSnakeCaseMember() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.nio.charset.Charset;",
            "import java.nio.charset.StandardCharsets;",
            "",
            "class A {",
            "  static final class StandardCharsetsUtf8 {",
            "    @BeforeTemplate",
            "    Charset before() {",
            "      return Charset.forName(\"UTF-8\");",
            "    }",
            "",
            "    @AfterTemplate",
            "    Charset after() {",
            "      return StandardCharsets.UTF_8;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationNewClassQualifiedType() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  static final class NewArrayList {",
            "    @BeforeTemplate",
            "    Object before() {",
            "      return new java.util.LinkedList<>();",
            "    }",
            "",
            "    @AfterTemplate",
            "    Object after() {",
            "      return new java.util.ArrayList<>();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationExpressionBlockVoidFirst() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.Collection;",
            "",
            "class A {",
            "  /* Void rule first → firstVoid=true: exercises reversed suffix assignment. */",
            "  static final class CollectionAddAllBlock {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elems) {",
            "      elems.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elems) {",
            "      addTo.addAll(elems);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddAllExpression {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elems) {",
            "      return addTo.containsAll(elems);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elems) {",
            "      return addTo.addAll(elems);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationBitwiseOps() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Bitwise AND: operator not in BINARY_OP_NAMES, literal contributes. */",
            "  static final class One {",
            "    @BeforeTemplate",
            "    int before(int a) {",
            "      return a % 2;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int a) {",
            "      return a & 1;",
            "    }",
            "  }",
            "",
            "  /* Bitwise complement: operator not in UNARY_OP_NAMES, literal contributes. */",
            "  static final class Zero {",
            "    @BeforeTemplate",
            "    int before() {",
            "      return -1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after() {",
            "      return ~0;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationMemberReferenceWithParameter() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.function.Supplier;",
            "",
            "class A {",
            "  static final class StringToCharArray {",
            "    @BeforeTemplate",
            "    Supplier<char[]> before(String str) {",
            "      return () -> str.toCharArray();",
            "    }",
            "",
            "    @AfterTemplate",
            "    Supplier<char[]> after(String str) {",
            "      return str::toCharArray;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationMemberSelectWithTypeVariableParameter() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  /* Type variable qualifier: name uses the variable letter, not its bound. */",
            "  static final class AIsEmpty<A extends java.util.Collection<?>> {",
            "    @BeforeTemplate",
            "    boolean before(A collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(A collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationMemberReferenceWithTypeVariableParameter() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.function.Supplier;",
            "",
            "class A {",
            "  /* Type variable qualifier in member reference: uses the variable letter. */",
            "  static final class AToCharArray<A extends String> {",
            "    @BeforeTemplate",
            "    Supplier<char[]> before(A str) {",
            "      return () -> str.toCharArray();",
            "    }",
            "",
            "    @AfterTemplate",
            "    Supplier<char[]> after(A str) {",
            "      return str::toCharArray;",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationMisnamedCastAndParenthesized() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongCastName {",
            "    @BeforeTemplate",
            "    int before(String str) {",
            "      return str.toCharArray().length;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(String str) {",
            "      return (int) (str.length());",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationNewClassWithLiteralArg() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.ArrayList;",
            "",
            "class A {",
            "  static final class NewArrayList42 {",
            "    @BeforeTemplate",
            "    ArrayList<String> before() {",
            "      return new ArrayList<>();",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after() {",
            "      return new ArrayList<>(42);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void identificationBoundaryCases() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Placeholder;",
            "",
            "class A {",
            "  /* Has @AfterTemplate but no @BeforeTemplate: not a rule. */",
            "  static final class NotARule1 {",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  /* Has @BeforeTemplate but no @AfterTemplate: not a rule. */",
            "  static final class NotARule2 {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  /* After template derives empty name (only placeholder call): not flagged. */",
            "  abstract static class PlaceholderOnly {",
            "    @Placeholder",
            "    abstract String transform(String input);",
            "",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return transform(str);",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Placeholder;",
            "",
            "class B {",
            "  /* Misnamed helper call alongside placeholder: exercises placeholder filter. */",
            "  // BUG: Diagnostic contains:",
            "  abstract static class WrongHelperName {",
            "    @Placeholder",
            "    abstract String transform(String input);",
            "",
            "    String helper(String s) {",
            "      return s;",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return helper(transform(str));",
            "    }",
            "  }",
            "}")
        .doTest();
  }
}
