package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

// XXX: Review parameter tests, list those first.
final class RefasterSourceCompatibilityTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterSourceCompatibility.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.common.collect.ImmutableList;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "import java.util.Map;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  class NonRefasterClass {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedNonRefasterClass {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  class NoBeforeTemplate {",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class NoAfterTemplate {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  class SameReturnType {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class VoidReturnType {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  class AfterIsSubtype {",
            "    @BeforeTemplate",
            "    CharSequence before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class AfterIsSubtypeGeneric {",
            "    @BeforeTemplate",
            "    List<? super String> before(String str) {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    ImmutableList<? super CharSequence> after(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "  }",
            "",
            "  class AfterReturnHasClassTypeVar<T> {",
            "    @BeforeTemplate",
            "    List<Void> before(String str) {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<T> after(String str) {",
            "      return List.of();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterIsSupertype {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterIsSupertypeGeneric {",
            "    @BeforeTemplate",
            "    ImmutableList<? extends String> before(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    ImmutableList<? extends CharSequence> after(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class VoidAfterNonVoidBefore {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class VoidBeforeNonVoidAfter {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class TwoTypeVarsReturnIncompatible<T, S> {",
            "    @BeforeTemplate",
            "    List<S> before(String str) {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<T> after(String str) {",
            "      return List.of();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterReturnTypeVarNotSubtype<T> {",
            "    @BeforeTemplate",
            "    ImmutableList<String> before(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<T> after(String str) {",
            "      return List.of();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedIncompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedCompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class MultipleBeforeTemplates {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before2(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleBeforeTemplatesOneIncompatible {",
            "    @BeforeTemplate",
            "    Object before1(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before2(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  class MultipleAfterTemplatesAllCompatible {",
            "    @BeforeTemplate",
            "    CharSequence before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after1(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after2(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleAfterTemplatesOneIncompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after1(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after2(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  class ParamsSameType {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  class AfterParamIsSupertype {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(CharSequence str) {",
            "      System.out.println(str);",
            "    }",
            "  }",
            "",
            "  class AfterParamIsSupertypeGeneric {",
            "    @BeforeTemplate",
            "    void before(ImmutableList<String> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(List<String> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  class MultipleBeforeParamsAllCompatible {",
            "    @BeforeTemplate",
            "    void before1(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(CharSequence str) {",
            "      System.out.println(str);",
            "    }",
            "  }",
            "",
            "  class AfterParamHasClassTypeVar<T> {",
            "    @BeforeTemplate",
            "    void before1(List<String> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(List<Void> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(List<T> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  class AfterParamHasClassTypeVarSubtype<T> {",
            "    @BeforeTemplate",
            "    void before(ImmutableList<String> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(List<T> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  class AfterParamTypeVarAppearsTwice<T> {",
            "    @BeforeTemplate",
            "    void before(Map<String, String> map) {",
            "      map.size();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Map<T, T> map) {",
            "      map.size();",
            "    }",
            "  }",
            "",
            "  class BeforeAndAfterShareClassTypeVar<T> {",
            "    @BeforeTemplate",
            "    List<T> before(List<T> list) {",
            "      return list.subList(0, list.size());",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<T> after(List<T> list) {",
            "      return list;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleBeforeParamsSomeCompatible {",
            "    @BeforeTemplate",
            "    void before1(CharSequence str) {",
            "      System.out.println(str);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterParamIsSubtype {",
            "    @BeforeTemplate",
            "    void before(CharSequence str) {",
            "      System.out.println(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterParamIsSubtypeGeneric {",
            "    @BeforeTemplate",
            "    void before(List<String> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(ImmutableList<String> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleParamsOneIncompatible {",
            "    @BeforeTemplate",
            "    void before(String p, CharSequence q) {",
            "      System.out.println(p.trim() + q);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String p, String q) {",
            "      System.out.println(p.strip() + q.strip());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterParamBoundedTypeVarIncompatible<T extends Number> {",
            "    @BeforeTemplate",
            "    void before(String x) {",
            "      System.out.println(x);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(T x) {",
            "      System.out.println(x);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterParamTypeVarConflictingBindings<T> {",
            "    @BeforeTemplate",
            "    void before(Map<String, Integer> map) {",
            "      map.size();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Map<T, T> map) {",
            "      map.size();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterParamTypeVarNestedListIncompatible<T> {",
            "    @BeforeTemplate",
            "    void before(List<ImmutableList<String>> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(List<List<T>> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleAfterParamTypeVarConflictingBindings<T> {",
            "    @BeforeTemplate",
            "    boolean before2(List<Integer> list1, List<String> list2) {",
            "      return list1.isEmpty() && list2.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(List<T> list1, List<T> list2) {",
            "        return list1.isEmpty() && list2.isEmpty();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterSourceCompatibility.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  class MissingAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class UnnecessaryAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class NonsensicalAnnotation {}",
            "",
            "  @PossibleSourceIncompatibility",
            "  class UnnecessaryAnnotationClassTypeVar<T> {",
            "    @BeforeTemplate",
            "    void before1(List<String> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(List<Void> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(List<T> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  class MissingAnnotationParamIncompatible {",
            "    @BeforeTemplate",
            "    void before(CharSequence str) {",
            "      System.out.println(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  @PossibleSourceIncompatibility",
            "  class MissingAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class UnnecessaryAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class NonsensicalAnnotation {}",
            "",
            "  class UnnecessaryAnnotationClassTypeVar<T> {",
            "    @BeforeTemplate",
            "    void before1(List<String> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(List<Void> list) {",
            "      list.isEmpty();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(List<T> list) {",
            "      list.isEmpty();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class MissingAnnotationParamIncompatible {",
            "    @BeforeTemplate",
            "    void before(CharSequence str) {",
            "      System.out.println(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "}")
        .doTest();
  }
}
