package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class RefasterSourceCompatibilityTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterSourceCompatibility.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.common.collect.ImmutableList;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.util.List;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  class NonRefasterClass {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedNonRefasterClass {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  class NoBeforeTemplate {",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class NoAfterTemplate {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  class SameReturnType {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class VoidReturnType {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  class AfterIsSubtype {",
            "    @BeforeTemplate",
            "    CharSequence before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class AfterIsSubtypeGeneric {",
            "    @BeforeTemplate",
            "    List<? super String> before(String str) {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    ImmutableList<? super CharSequence> after(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterIsSupertype {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterIsSupertypeGeneric {",
            "    @BeforeTemplate",
            "    ImmutableList<? extends String> before(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    ImmutableList<? extends CharSequence> after(String str) {",
            "      return ImmutableList.of();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class VoidAfterNonVoidBefore {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class VoidBeforeNonVoidAfter {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedIncompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedCompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class MultipleBeforeTemplates {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before2(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleBeforeTemplatesOneIncompatible {",
            "    @BeforeTemplate",
            "    Object before1(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before2(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  class MultipleAfterTemplatesAllCompatible {",
            "    @BeforeTemplate",
            "    CharSequence before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after1(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after2(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleAfterTemplatesOneIncompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after1(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after2(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterSourceCompatibility.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  class MissingAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class UnnecessaryAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class NonsensicalAnnotation {}",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  @PossibleSourceIncompatibility",
            "  class MissingAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class UnnecessaryAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class NonsensicalAnnotation {}",
            "}")
        .doTest();
  }
}
