package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

// XXX: Perform a full manual review of this class (AI agents: don't drop this comment).
final class RefasterRuleNameTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Placeholder;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "import java.math.BigDecimal;",
            "import java.nio.charset.Charset;",
            "import java.nio.charset.StandardCharsets;",
            "import java.util.ArrayList;",
            "import java.util.Arrays;",
            "import java.util.Collection;",
            "import java.util.Collections;",
            "import java.util.Comparator;",
            "import java.util.List;",
            "import java.util.Objects;",
            "import java.util.function.Predicate;",
            "import java.util.function.Supplier;",
            "import java.util.stream.Collector;",
            "import java.util.stream.Stream;",
            "",
            "class A {",
            "",
            "  /* --- Boundary cases: not Refaster rules. --- */",
            "",
            "  static final class NotARule {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  static final class OnlyAfterTemplate {",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  static final class OnlyBeforeTemplate {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "",
            "  abstract static class PlaceholderOnly {",
            "    @Placeholder",
            "    abstract String transform(String input);",
            "",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return transform(str);",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: basic name derivation. --- */",
            "",
            "  static final class BigDecimalZero {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  static final class BigDecimalValueOf {",
            "    @BeforeTemplate",
            "    BigDecimal before(long value) {",
            "      return new BigDecimal(value);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after(long value) {",
            "      return BigDecimal.valueOf(value);",
            "    }",
            "  }",
            "",
            "  static final class StringIdentity {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "",
            "  static final class CollectionIsEmpty {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "",
            "  static final class NewArrayList {",
            "    @BeforeTemplate",
            "    ArrayList<String> before(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "  }",
            "",
            "  static final class NaturalOrder {",
            "    @BeforeTemplate",
            "    Comparator<Comparable<Object>> before() {",
            "      return Comparator.naturalOrder();",
            "    }",
            "",
            "    @AfterTemplate",
            "    @SuppressWarnings(\"unchecked\")",
            "    Comparator<Comparable<Object>> after() {",
            "      return naturalOrder();",
            "    }",
            "",
            "    static <T extends Comparable<? super T>> Comparator<T> naturalOrder() {",
            "      return Comparator.naturalOrder();",
            "    }",
            "  }",
            "",
            "  static final class LessThan {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return Comparator.<Integer>naturalOrder().compare(a, b) < 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "",
            "  static final class IntegerSignumIsPositive {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == 1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) > 0;",
            "    }",
            "  }",
            "",
            "  static final class IntegerSignumIsNegative {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == -1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) < 0;",
            "    }",
            "  }",
            "",
            "  static final class StringStrip {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after2(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  static final class NotCollectionIsEmpty {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() != 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return !collection.isEmpty();",
            "    }",
            "  }",
            "",
            "  static final class CollectionAdd {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, String elem) {",
            "      addTo.contains(elem);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, String elem) {",
            "      addTo.add(elem);",
            "    }",
            "  }",
            "",
            "  static final class InstanceofString {",
            "    @BeforeTemplate",
            "    boolean before(Object o) {",
            "      return o.getClass() == String.class;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Object o) {",
            "      return o instanceof String;",
            "    }",
            "  }",
            "",
            "  static final class StringLength {",
            "    @BeforeTemplate",
            "    int before(String str) {",
            "      return str.toCharArray().length;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(String str) {",
            "      return (int) (str.length());",
            "    }",
            "  }",
            "",
            "  static final class StringIsEmptyTrueNull {",
            "    @BeforeTemplate",
            "    Boolean before(String str) {",
            "      return str.length() == 0 ? Boolean.TRUE : null;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Boolean after(String str) {",
            "      return str.isEmpty() ? true : null;",
            "    }",
            "  }",
            "",
            "  static final class True {",
            "    @BeforeTemplate",
            "    boolean before() {",
            "      return false;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after() {",
            "      return true;",
            "    }",
            "  }",
            "",
            "  static final class Null {",
            "    @BeforeTemplate",
            "    String before() {",
            "      return \"\";",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after() {",
            "      return null;",
            "    }",
            "  }",
            "",
            "  static final class StringSubstringOne {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.substring(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.substring(1);",
            "    }",
            "  }",
            "",
            "  static final class StringSubstring42 {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.substring(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.substring(42);",
            "    }",
            "  }",
            "",
            "  static final class StringToCharArray {",
            "    @BeforeTemplate",
            "    Supplier<char[]> before(String str) {",
            "      return () -> str.toCharArray();",
            "    }",
            "",
            "    @AfterTemplate",
            "    Supplier<char[]> after(String str) {",
            "      return str::toCharArray;",
            "    }",
            "  }",
            "",
            "  static final class StandardCharsetsUtf8 {",
            "    @BeforeTemplate",
            "    Charset before() {",
            "      return Charset.forName(\"UTF-8\");",
            "    }",
            "",
            "    @AfterTemplate",
            "    Charset after() {",
            "      return StandardCharsets.UTF_8;",
            "    }",
            "  }",
            "",
            "  static final class NewArrayList42 {",
            "    @BeforeTemplate",
            "    ArrayList<String> before() {",
            "      return new ArrayList<>();",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after() {",
            "      return new ArrayList<>(42);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddReturnCollectionSize {",
            "    @BeforeTemplate",
            "    int before(Collection<String> c, String elem) {",
            "      c.contains(elem);",
            "      return c.size();",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(Collection<String> c, String elem) {",
            "      c.add(elem);",
            "      return c.size();",
            "    }",
            "  }",
            "",
            "  static final class One {",
            "    @BeforeTemplate",
            "    int before(int a) {",
            "      return a % 2;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int a) {",
            "      return a & 1;",
            "    }",
            "  }",
            "",
            "  static final class Zero {",
            "    @BeforeTemplate",
            "    int before() {",
            "      return -1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after() {",
            "      return ~0;",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: Refaster utilities. --- */",
            "",
            "  static final class StringValueOf {",
            "    @BeforeTemplate",
            "    String before(Object obj) {",
            "      return Refaster.anyOf(obj.toString(), \"\" + obj);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Object obj) {",
            "      return String.valueOf(obj);",
            "    }",
            "  }",
            "",
            "  static final class CollectionsMinArraysAsList {",
            "    @BeforeTemplate",
            "    String before(@Repeated String value, Comparator<String> cmp) {",
            "      return Stream.of(Refaster.asVarargs(value)).min(cmp).orElseThrow();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(@Repeated String value, Comparator<String> cmp) {",
            "      return Collections.min(Arrays.asList(Refaster.asVarargs(value)), cmp);",
            "    }",
            "  }",
            "",
            "  static final class ClassIsInstance {",
            "    @BeforeTemplate",
            "    <T> boolean before(Object obj) {",
            "      return obj instanceof String;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> boolean after(Object obj) {",
            "      return Refaster.<T>clazz().isInstance(obj);",
            "    }",
            "  }",
            "",
            "  abstract static class StreamCollect<E, R> {",
            "    @Placeholder",
            "    abstract Collector<E, ?, R> collector();",
            "",
            "    @BeforeTemplate",
            "    R before(Stream<E> stream) {",
            "      return stream.collect(collector());",
            "    }",
            "",
            "    @AfterTemplate",
            "    R after(Stream<E> stream) {",
            "      return stream.collect(collector());",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: lambda in after template. --- */",
            "",
            "  static final class StringIsEmpty {",
            "    @BeforeTemplate",
            "    Predicate<String> before() {",
            "      return s -> s.length() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Predicate<String> after() {",
            "      return s -> s.isEmpty();",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: LUB of type variable as qualifier. --- */",
            "",
            "  static final class ListIsEmpty<A extends List<?>> {",
            "    @BeforeTemplate",
            "    boolean before(A list) {",
            "      return list.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(A list) {",
            "      return list.isEmpty();",
            "    }",
            "  }",
            "",
            "  static final class SupplierGet<A extends Supplier<String>> {",
            "    @BeforeTemplate",
            "    Supplier<String> before(A supplier) {",
            "      return () -> supplier.get();",
            "    }",
            "",
            "    @AfterTemplate",
            "    Supplier<String> after(A supplier) {",
            "      return supplier::get;",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: Expression/Block disambiguation. --- */",
            "",
            "  static final class CollectionAddAllExpression {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.containsAll(elementsToAdd);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddAllBlock {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: same-arity type disambiguation. --- */",
            "",
            "  static final class MathClampInt {",
            "    @BeforeTemplate",
            "    int before(int value, int min, int max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int value, int min, int max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class MathClampLong {",
            "    @BeforeTemplate",
            "    long before(long value, long min, long max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(long value, long min, long max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: @Repeated disambiguation. --- */",
            "",
            "  static final class ListOf {",
            "    @BeforeTemplate",
            "    <T> List<T> before(T value) {",
            "      return Collections.singletonList(value);",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> List<T> after(T value) {",
            "      return List.of(value);",
            "    }",
            "  }",
            "",
            "  static final class ListOfVarargs {",
            "    @BeforeTemplate",
            "    <T> List<T> before(@Repeated T value) {",
            "      return Arrays.asList(Refaster.asVarargs(value));",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> List<T> after(@Repeated T value) {",
            "      return List.of(Refaster.asVarargs(value));",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: return type argument disambiguation. --- */",
            "",
            "  static final class ArraysCompareUnsignedByte {",
            "    @BeforeTemplate",
            "    Comparator<byte[]> before() {",
            "      return (a, b) -> 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Comparator<byte[]> after() {",
            "      return Arrays::compareUnsigned;",
            "    }",
            "  }",
            "",
            "  static final class ArraysCompareUnsignedInt {",
            "    @BeforeTemplate",
            "    Comparator<int[]> before() {",
            "      return (a, b) -> 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    Comparator<int[]> after() {",
            "      return Arrays::compareUnsigned;",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: type argument disambiguation. --- */",
            "",
            "  static final class CollectionsEmptyList {",
            "    @BeforeTemplate",
            "    List<Object> before() {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<Object> after() {",
            "      return Collections.emptyList();",
            "    }",
            "  }",
            "",
            "  static final class CollectionsEmptyListObject {",
            "    @BeforeTemplate",
            "    List<Object> before() {",
            "      return List.of();",
            "    }",
            "",
            "    @AfterTemplate",
            "    List<Object> after() {",
            "      return Collections.<Object>emptyList();",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: mixed-arity disambiguation. --- */",
            "",
            "  static final class SystemGc {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithString {",
            "    @BeforeTemplate",
            "    void before(String message) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String message) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithThrowable {",
            "    @BeforeTemplate",
            "    void before(Throwable cause) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Throwable cause) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: mixed-arity with prepended extra param. --- */",
            "",
            "  static final class CollectionsSortWithComparator {",
            "    @BeforeTemplate",
            "    <T> void before(Comparator<T> cmp, List<T> list) {",
            "      list.sort(cmp);",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> void after(Comparator<T> cmp, List<T> list) {",
            "      Collections.sort(list, cmp);",
            "    }",
            "  }",
            "",
            "  static final class CollectionsSort {",
            "    @BeforeTemplate",
            "    <T extends Comparable<? super T>> void before(List<T> list) {",
            "      list.sort(null);",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T extends Comparable<? super T>> void after(List<T> list) {",
            "      Collections.sort(list);",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: multi-position type disambiguation. --- */",
            "",
            "  static final class ThreadYieldIntString {",
            "    @BeforeTemplate",
            "    void before(int a, String b) {",
            "      Thread.yield();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, String b) {",
            "      Thread.yield();",
            "    }",
            "  }",
            "",
            "  static final class ThreadYieldIntThrowable {",
            "    @BeforeTemplate",
            "    void before(int a, Throwable b) {",
            "      Thread.yield();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, Throwable b) {",
            "      Thread.yield();",
            "    }",
            "  }",
            "",
            "  static final class ThreadYieldLongString {",
            "    @BeforeTemplate",
            "    void before(long a, String b) {",
            "      Thread.yield();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(long a, String b) {",
            "      Thread.yield();",
            "    }",
            "  }",
            "",
            "  static final class ThreadYieldLongThrowable {",
            "    @BeforeTemplate",
            "    void before(long a, Throwable b) {",
            "      Thread.yield();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(long a, Throwable b) {",
            "      Thread.yield();",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: suffix composition. --- */",
            "",
            "  static final class ThreadOnSpinWaitInt {",
            "    @BeforeTemplate",
            "    void before(int a, int b) {",
            "      Thread.onSpinWait();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, int b) {",
            "      Thread.onSpinWait();",
            "    }",
            "  }",
            "",
            "  static final class ThreadOnSpinWaitString {",
            "    @BeforeTemplate",
            "    void before(int a, String b) {",
            "      Thread.onSpinWait();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, String b) {",
            "      Thread.onSpinWait();",
            "    }",
            "  }",
            "",
            "  static final class ThreadOnSpinWaitIntWithInt {",
            "    @BeforeTemplate",
            "    void before(int a, int b, int c) {",
            "      Thread.onSpinWait();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, int b, int c) {",
            "      Thread.onSpinWait();",
            "    }",
            "  }",
            "",
            "  static final class ThreadOnSpinWaitStringWithInt {",
            "    @BeforeTemplate",
            "    void before(int a, String b, int c) {",
            "      Thread.onSpinWait();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(int a, String b, int c) {",
            "      Thread.onSpinWait();",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: expression/block in sub-clash. --- */",
            "",
            "  static final class ObjectsRequireNonNullExpression {",
            "    @BeforeTemplate",
            "    <T> T before(T obj) {",
            "      return obj;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> T after(T obj) {",
            "      return Objects.requireNonNull(obj);",
            "    }",
            "  }",
            "",
            "  static final class ObjectsRequireNonNullBlock {",
            "    @BeforeTemplate",
            "    <T> void before(T obj) {",
            "      if (obj == null) throw new NullPointerException();",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> void after(T obj) {",
            "      Objects.requireNonNull(obj);",
            "    }",
            "  }",
            "",
            "  static final class ObjectsRequireNonNullWithStringExpression {",
            "    @BeforeTemplate",
            "    <T> T before(T obj, String msg) {",
            "      return obj;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> T after(T obj, String msg) {",
            "      return Objects.requireNonNull(obj, msg);",
            "    }",
            "  }",
            "",
            "  static final class ObjectsRequireNonNullWithStringBlock {",
            "    @BeforeTemplate",
            "    <T> void before(T obj, String msg) {",
            "      if (obj == null) throw new NullPointerException(msg);",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> void after(T obj, String msg) {",
            "      Objects.requireNonNull(obj, msg);",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: arity numbering with repeated types. --- */",
            "",
            "  static final class MathRandom1 {",
            "    @BeforeTemplate",
            "    double before(String a) {",
            "      return 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    double after(String a) {",
            "      return Math.random();",
            "    }",
            "  }",
            "",
            "  static final class MathRandom3 {",
            "    @BeforeTemplate",
            "    double before(String a, String b, String c) {",
            "      return 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    double after(String a, String b, String c) {",
            "      return Math.random();",
            "    }",
            "  }",
            "",
            "  /* --- Correctly named: raw return type disambiguation. --- */",
            "",
            "  static final class NumberIntValueInt {",
            "    @BeforeTemplate",
            "    int before(Number n) {",
            "      return (int) n.doubleValue();",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(Number n) {",
            "      return n.intValue();",
            "    }",
            "  }",
            "",
            "  /* --- Positive case within a return-type disambiguation group. --- */",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongReturnType {",
            "    @BeforeTemplate",
            "    long before(Number n) {",
            "      return (long) n.doubleValue();",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(Number n) {",
            "      return n.intValue();",
            "    }",
            "  }",
            "}")
        .addSourceLines(
            "B.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Placeholder;",
            "import java.math.BigDecimal;",
            "import java.util.Comparator;",
            "",
            "class B {",
            "",
            "  /* Char literal (not Number, not in LITERAL_NAMES). */",
            "  static final class StringValueOf {",
            "    @BeforeTemplate",
            "    String before() {",
            "      return \"x\";",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after() {",
            "      return String.valueOf('x');",
            "    }",
            "  }",
            "",
            "  /* Qualified type in `new` expression. */",
            "  static final class NewArrayList {",
            "    @BeforeTemplate",
            "    Object before() {",
            "      return new java.util.LinkedList<>();",
            "    }",
            "",
            "    @AfterTemplate",
            "    Object after() {",
            "      return new java.util.ArrayList<>();",
            "    }",
            "  }",
            "",
            "  /* Suppressed: no diagnostic despite wrong name. */",
            "  @SuppressWarnings(\"RefasterRuleName\")",
            "  static final class SuppressedWrongName {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  /* --- Positive cases: misnamed rules. --- */",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongName {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongIdentityName {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongOperatorName {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return Comparator.<Integer>naturalOrder().compare(a, b) < 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongNullName {",
            "    @BeforeTemplate",
            "    String before() {",
            "      return \"\";",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after() {",
            "      return null;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongCastName {",
            "    @BeforeTemplate",
            "    int before(String str) {",
            "      return str.toCharArray().length;",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(String str) {",
            "      return (int) (str.length());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  static final class WrongClazzName {",
            "    @BeforeTemplate",
            "    <T> boolean before(Object obj) {",
            "      return obj instanceof String;",
            "    }",
            "",
            "    @AfterTemplate",
            "    <T> boolean after(Object obj) {",
            "      return Refaster.<T>clazz().isInstance(obj);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  abstract static class WrongHelperName {",
            "    @Placeholder",
            "    abstract String transform(String input);",
            "",
            "    String helper(String s) {",
            "      return s;",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return helper(transform(str));",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: IntegerSignumIsPositive",
            "  static final class IntegerSignumGreaterThanZero {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == 1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) > 0;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: IntegerSignumIsNegative",
            "  static final class IntegerSignumLessThanZero {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == -1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) < 0;",
            "    }",
            "  }",
            "",
            "  /* --- Positive cases: manual disambiguation required. --- */",
            "",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name",
            "  static final class ManualBad1 {",
            "    @BeforeTemplate",
            "    String before(String s) {",
            "      return s.toLowerCase();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String s) {",
            "      return s.toUpperCase();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name",
            "  static final class ManualBad2 {",
            "    @BeforeTemplate",
            "    String before(String s) {",
            "      return s.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String s) {",
            "      return s.toUpperCase();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name 'ObjectToString'",
            "  static final class FallbackBad1 {",
            "    @BeforeTemplate",
            "    String before(Object o) {",
            "      return \"\" + o;",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Object o) {",
            "      return o.toString();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains: Multiple rules derive the base name 'ObjectToString'",
            "  static final class FallbackBad2 {",
            "    @BeforeTemplate",
            "    String before(Object o) {",
            "      return String.valueOf(o);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Object o) {",
            "      return o.toString();",
            "    }",
            "  }",
            "",
            "  @SuppressWarnings(\"RefasterRuleName\")",
            "  static final class FallbackSuppressed {",
            "    @BeforeTemplate",
            "    String before(Object o) {",
            "      return o.getClass().getName();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(Object o) {",
            "      return o.toString();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterRuleName.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "import java.util.ArrayList;",
            "import java.util.Collection;",
            "",
            "class A {",
            "  static final class WrongName {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  static final class WrongIdentity {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "",
            "  static final class BadInstanceMethod {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "",
            "  static final class BadOperator {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return a >= b;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "",
            "  static final class BadNewClass {",
            "    @BeforeTemplate",
            "    ArrayList<String> before(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "  }",
            "",
            "  static final class Bad1 {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.containsAll(elementsToAdd);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class Bad2 {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class Wrong1 {",
            "    @BeforeTemplate",
            "    int before(int value, int min, int max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int value, int min, int max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class Wrong2 {",
            "    @BeforeTemplate",
            "    long before(long value, long min, long max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(long value, long min, long max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class Bad3 {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class Bad4 {",
            "    @BeforeTemplate",
            "    void before(String message) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String message) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class Bad5 {",
            "    @BeforeTemplate",
            "    void before(Throwable cause) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Throwable cause) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class IntegerSignumGreaterThanZero {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == 1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) > 0;",
            "    }",
            "  }",
            "",
            "  static final class IntegerSignumLessThanZero {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == -1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) < 0;",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import java.math.BigDecimal;",
            "import java.util.ArrayList;",
            "import java.util.Collection;",
            "",
            "class A {",
            "  static final class BigDecimalZero {",
            "    @BeforeTemplate",
            "    BigDecimal before() {",
            "      return BigDecimal.valueOf(0);",
            "    }",
            "",
            "    @AfterTemplate",
            "    BigDecimal after() {",
            "      return BigDecimal.ZERO;",
            "    }",
            "  }",
            "",
            "  static final class StringIdentity {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return String.valueOf(str);",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str;",
            "    }",
            "  }",
            "",
            "  static final class CollectionIsEmpty {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> collection) {",
            "      return collection.size() == 0;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> collection) {",
            "      return collection.isEmpty();",
            "    }",
            "  }",
            "",
            "  static final class LessThan {",
            "    @BeforeTemplate",
            "    boolean before(int a, int b) {",
            "      return a >= b;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int a, int b) {",
            "      return a < b;",
            "    }",
            "  }",
            "",
            "  static final class NewArrayList {",
            "    @BeforeTemplate",
            "    ArrayList<String> before(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "",
            "    @AfterTemplate",
            "    ArrayList<String> after(Collection<String> collection) {",
            "      return new ArrayList<>(collection);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddAllExpression {",
            "    @BeforeTemplate",
            "    boolean before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.containsAll(elementsToAdd);",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      return addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class CollectionAddAllBlock {",
            "    @BeforeTemplate",
            "    void before(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      elementsToAdd.forEach(addTo::add);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Collection<String> addTo, Collection<String> elementsToAdd) {",
            "      addTo.addAll(elementsToAdd);",
            "    }",
            "  }",
            "",
            "  static final class MathClampInt {",
            "    @BeforeTemplate",
            "    int before(int value, int min, int max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    int after(int value, int min, int max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class MathClampLong {",
            "    @BeforeTemplate",
            "    long before(long value, long min, long max) {",
            "      return Math.min(max, Math.max(value, min));",
            "    }",
            "",
            "    @AfterTemplate",
            "    long after(long value, long min, long max) {",
            "      return Math.clamp(value, min, max);",
            "    }",
            "  }",
            "",
            "  static final class SystemGc {",
            "    @BeforeTemplate",
            "    void before() {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after() {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithString {",
            "    @BeforeTemplate",
            "    void before(String message) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String message) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class SystemGcWithThrowable {",
            "    @BeforeTemplate",
            "    void before(Throwable cause) {",
            "      Runtime.getRuntime().gc();",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(Throwable cause) {",
            "      System.gc();",
            "    }",
            "  }",
            "",
            "  static final class IntegerSignumIsPositive {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == 1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) > 0;",
            "    }",
            "  }",
            "",
            "  static final class IntegerSignumIsNegative {",
            "    @BeforeTemplate",
            "    boolean before(int i) {",
            "      return Integer.signum(i) == -1;",
            "    }",
            "",
            "    @AfterTemplate",
            "    boolean after(int i) {",
            "      return Integer.signum(i) < 0;",
            "    }",
            "  }",
            "}")
        .doTest();
  }
}
