package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.BugCheckerRefactoringTestHelper.TestMode;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class RefasterSourceCompatibilityCheckTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterSourceCompatibilityCheck.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  class NonRefasterClass {",
            "    String method() {",
            "      return \"\";",
            "    }",
            "  }",
            "",
            "  class SameReturnType {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class AfterIsSubtype {",
            "    @BeforeTemplate",
            "    CharSequence before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class VoidReturnType {",
            "    @BeforeTemplate",
            "    void before(String str) {",
            "      System.out.println(str.trim());",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String str) {",
            "      System.out.println(str.strip());",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class AfterIsSupertype {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  class AnnotatedIncompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  @PossibleSourceIncompatibility",
            "  // BUG: Diagnostic contains:",
            "  class AnnotatedCompatible {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "",
            "  class MultipleBeforeTemplates {",
            "    @BeforeTemplate",
            "    String before1(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before2(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultipleBeforeTemplatesOneIncompatible {",
            "    @BeforeTemplate",
            "    Object before1(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @BeforeTemplate",
            "    String before2(String str) {",
            "      return str.strip();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.stripLeading();",
            "    }",
            "  }",
            "",
            "  class NoAfterTemplate {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterSourceCompatibilityCheck.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "",
            "class A {",
            "  class MissingAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class A {",
            "  @PossibleSourceIncompatibility",
            "  class MissingAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    CharSequence after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "}")
        .addInputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class B {",
            "  @PossibleSourceIncompatibility",
            "  class UnnecessaryAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "B.java",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import tech.picnic.errorprone.refaster.annotation.PossibleSourceIncompatibility;",
            "",
            "class B {",
            "  class UnnecessaryAnnotation {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str.trim();",
            "    }",
            "",
            "    @AfterTemplate",
            "    String after(String str) {",
            "      return str.strip();",
            "    }",
            "  }",
            "}")
        .doTest(TestMode.TEXT_MATCH);
  }
}
