package tech.picnic.errorprone.guidelines.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

// XXX: Fully review this class.
final class RefasterParameterNamingTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(RefasterParameterNaming.class, getClass())
        .addSourceLines(
            "A.java",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "import java.util.OptionalInt;",
            "",
            "class A {",
            "  static void helper(String value) {}",
            "",
            "  static void consume(String text, int count) {}",
            "",
            "  static int useStr(String str) {",
            "    return str.length();",
            "  }",
            "",
            "  static String format(String format, Object... args) {",
            "    return format;",
            "  }",
            "",
            "  static void takeExpression(boolean expression) {}",
            "",
            "  static void takeFromIndex(String str, int fromIndex) {}",
            "",
            "  class ParameterAlreadyNamedCorrectly {",
            "    @BeforeTemplate",
            "    void before(String value) {",
            "      helper(value);",
            "    }",
            "  }",
            "",
            "  class NoTemplateMethodsPresent {",
            "    void notATemplate(String a) {",
            "      helper(a);",
            "    }",
            "  }",
            "",
            "  class ParameterPassedToMethodWithSyntheticName<E> {",
            "    @BeforeTemplate",
            "    boolean before(java.util.Collection<E> collection, E element) {",
            "      return collection.contains(element);",
            "    }",
            "  }",
            "",
            "  class BooleanWrapperParameterWithNoInvocation {",
            "    @BeforeTemplate",
            "    Boolean before(Boolean a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  class ParametersAlreadyNamedWithSuffix {",
            "    @BeforeTemplate",
            "    void before(String value1, String value2) {",
            "      helper(value1);",
            "      helper(value2);",
            "    }",
            "  }",
            "",
            "  class SuffixFamilyAlreadyCorrectWhenContextOrderDiffersFromDeclOrder {",
            "    @BeforeTemplate",
            "    int before(String str1, String str2) {",
            "      return useStr(str2) + str1.length();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterUsedOnlyInNonInvocationContext {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterUsedOnlyInRefasterAnyOf {",
            "    @BeforeTemplate",
            "    String before(String a, String b) {",
            "      return Refaster.anyOf(a, b);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return A.format(\"%s\", a);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterPassedToRefasterEmitComment {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return Refaster.emitCommentBefore(\"foo\", a);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterNameDiffersFromDerived {",
            "    @BeforeTemplate",
            "    void before(String x) {",
            "      helper(x);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class NameCollision {",
            "    @BeforeTemplate",
            "    void before(String a, String b) {",
            "      helper(a);",
            "      helper(b);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class RepeatedParameterAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String a, @Repeated Object b) {",
            "      return A.format(a, b);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class PrimitiveTypeParameter {",
            "    @BeforeTemplate",
            "    int before(int a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class MultiPartTypeWithKeywordLastWord {",
            "    @BeforeTemplate",
            "    int before(OptionalInt a) {",
            "      return a.getAsInt();",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class HigherArityBeforeTemplateBreaksTie {",
            "    @BeforeTemplate",
            "    void before1(String a) {",
            "      helper(a);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String a, int b) {",
            "      A.consume(a, b);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterAsArrayDimension {",
            "    @BeforeTemplate",
            "    String[] before(int a) {",
            "      return new String[a];",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterAsIfCondition {",
            "    @BeforeTemplate",
            "    void before(boolean a) {",
            "      if (a) {}",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterAsNegatedIfCondition {",
            "    @BeforeTemplate",
            "    void before(boolean a) {",
            "      if (!a) {}",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class FixedNameInNumberedFamilyBool {",
            "    @BeforeTemplate",
            "    boolean before(boolean b1, boolean b) {",
            "      return b;",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class FixedNameInNumberedFamilyStr {",
            "    @BeforeTemplate",
            "    int before(String str1, String str) {",
            "      return str.length();",
            "    }",
            "  }",
            "",
            "  class ParameterAlreadyNamedExpressionViaUnary {",
            "    @BeforeTemplate",
            "    void before(boolean expression) {",
            "      takeExpression(!expression);",
            "    }",
            "  }",
            "",
            "  class ParameterAlreadyNamedFromIndexViaBinary {",
            "    @BeforeTemplate",
            "    void before(String str, int fromIndex) {",
            "      takeFromIndex(str, fromIndex - 1);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterPassedViaUnary {",
            "    @BeforeTemplate",
            "    void before(boolean a) {",
            "      takeExpression(!a);",
            "    }",
            "  }",
            "",
            "  // BUG: Diagnostic contains:",
            "  class ParameterPassedViaBinaryWithConstant {",
            "    @BeforeTemplate",
            "    void before(String str, int a) {",
            "      takeFromIndex(str, a - 1);",
            "    }",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(RefasterParameterNaming.class, getClass())
        .addInputLines(
            "A.java",
            "import com.google.common.collect.ImmutableList;",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Matches;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "import java.util.Comparator;",
            "import java.util.List;",
            "import java.util.OptionalInt;",
            "import java.util.function.Function;",
            "import tech.picnic.errorprone.refaster.matchers.IsEmpty;",
            "import tech.picnic.errorprone.refaster.matchers.IsIdentityOperation;",
            "",
            "class A {",
            "  static void helper(String value, int count) {}",
            "",
            "  static void helperStr(String str1) {}",
            "",
            "  static String other(String text) {",
            "    return text;",
            "  }",
            "",
            "  static String format(String format, Object... args) {",
            "    return format;",
            "  }",
            "",
            "  interface AsyncCache<K, V> {}",
            "",
            "  interface AsyncLoadingCache<K, V> {}",
            "",
            "  interface PublisherProbe<T> {}",
            "",
            "  static void takeExpression(boolean expression) {}",
            "",
            "  static void takeFromIndex(String str, int fromIndex) {}",
            "",
            "  class SimpleRename {",
            "    @BeforeTemplate",
            "    void before(String x) {",
            "      helper(x, 1);",
            "    }",
            "  }",
            "",
            "  class MultipleParameters {",
            "    @BeforeTemplate",
            "    void before(String a, int b) {",
            "      helper(a, b);",
            "    }",
            "  }",
            "",
            "  class AfterTemplateTakesPriority {",
            "    @BeforeTemplate",
            "    void before(String a) {",
            "      helper(a, 1);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String a) {",
            "      other(a);",
            "    }",
            "  }",
            "",
            "  class MixedRenameAndTypeFallback {",
            "    @BeforeTemplate",
            "    String before(String x, String y) {",
            "      helper(x, 1);",
            "      return y;",
            "    }",
            "  }",
            "",
            "  class FirstInvocationWins {",
            "    @BeforeTemplate",
            "    void before(String a) {",
            "      helper(a, 1);",
            "      other(a);",
            "    }",
            "  }",
            "",
            "  class NestedInvocation {",
            "    @BeforeTemplate",
            "    void before(String a, int b) {",
            "      helper(other(a), b);",
            "    }",
            "  }",
            "",
            "  class HigherArityBreaksTie {",
            "    @BeforeTemplate",
            "    void before1(String a) {",
            "      helper(a, 1);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String a, int b) {",
            "      other(a);",
            "    }",
            "  }",
            "",
            "  class ConflictResolutionWithSuffix {",
            "    @BeforeTemplate",
            "    void before(String a, String b) {",
            "      helper(a, 1);",
            "      helper(b, 1);",
            "    }",
            "  }",
            "",
            "  class SwapRename {",
            "    @BeforeTemplate",
            "    void before(String text, String value) {",
            "      helper(text, 1);",
            "      other(value);",
            "    }",
            "  }",
            "",
            "  class RepeatedParameterViaAsVarargs {",
            "    @BeforeTemplate",
            "    String before(String a, @Repeated Object b) {",
            "      return A.format(a, Refaster.asVarargs(b));",
            "    }",
            "  }",
            "",
            "  class TypeFallbackString {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackImmutableList {",
            "    @BeforeTemplate",
            "    int before(ImmutableList<String> a) {",
            "      return a.size();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackArray {",
            "    @BeforeTemplate",
            "    int before(String[] a) {",
            "      return a.length;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackComparator {",
            "    @BeforeTemplate",
            "    int before(Comparator<String> a) {",
            "      return a.compare(\"x\", \"y\");",
            "    }",
            "  }",
            "",
            "  class TypeFallbackStringBuilder {",
            "    @BeforeTemplate",
            "    String before(StringBuilder a) {",
            "      return a.toString();",
            "    }",
            "  }",
            "",
            "  class TypeConflict {",
            "    @BeforeTemplate",
            "    String before(String a, String b) {",
            "      return a + b;",
            "    }",
            "  }",
            "",
            "  class MixedInvocationAndTypeFallback {",
            "    @BeforeTemplate",
            "    String before(String a, String b) {",
            "      helper(a, 1);",
            "      return b;",
            "    }",
            "  }",
            "",
            "  class PrimitiveFallback {",
            "    @BeforeTemplate",
            "    int before(int a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  class KeywordFallbackMultiPart {",
            "    @BeforeTemplate",
            "    int before(OptionalInt a) {",
            "      return a.getAsInt();",
            "    }",
            "  }",
            "",
            "  class NonRepeatedAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String a) {",
            "      return A.format(\"%s\", a);",
            "    }",
            "  }",
            "",
            "  class CorrectlyNamedParamWithConflict {",
            "    @BeforeTemplate",
            "    void before(String value, String x) {",
            "      helper(value, 1);",
            "      helper(x, 1);",
            "    }",
            "  }",
            "",
            "  class OneParamAlreadyCorrect {",
            "    @BeforeTemplate",
            "    void before(String text, String x) {",
            "      other(text);",
            "      helper(x, 1);",
            "    }",
            "  }",
            "",
            "  class ConflictWithOccupiedSuffix<E> {",
            "    @BeforeTemplate",
            "    void before(E value1, String a, String b) {",
            "      helper(a, 2);",
            "      helper(b, 3);",
            "    }",
            "  }",
            "",
            "  class ArrayDimensionNaming {",
            "    @BeforeTemplate",
            "    String[] before(int a) {",
            "      return new String[a];",
            "    }",
            "  }",
            "",
            "  class IfConditionNaming {",
            "    @BeforeTemplate",
            "    void before(boolean a) {",
            "      if (a) {}",
            "    }",
            "  }",
            "",
            "  class NegatedIfConditionNaming {",
            "    @BeforeTemplate",
            "    void before(boolean a) {",
            "      if (!a) {}",
            "    }",
            "  }",
            "",
            "  class MatchesIsIdentityFunction {",
            "    @BeforeTemplate",
            "    <T, R> Function<T, R> before(@Matches(IsIdentityOperation.class) Function<T, R> a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  class MatchesIsEmptyList {",
            "    @BeforeTemplate",
            "    int before(@Matches(IsEmpty.class) List<String> a) {",
            "      return a.size();",
            "    }",
            "  }",
            "",
            "  class SuffixFamilyBool {",
            "    @BeforeTemplate",
            "    boolean before(Boolean b1, boolean a) {",
            "      return a;",
            "    }",
            "  }",
            "",
            "  class SuffixFamilyStr {",
            "    @BeforeTemplate",
            "    int before(String str1, String a) {",
            "      helperStr(str1);",
            "      return a.length();",
            "    }",
            "  }",
            "",
            "  class FixedNameInNumberedFamilyBool {",
            "    @BeforeTemplate",
            "    boolean before(boolean b1, boolean b) {",
            "      return b;",
            "    }",
            "  }",
            "",
            "  class FixedNameInNumberedFamilyStr {",
            "    @BeforeTemplate",
            "    int before(String str1, String str) {",
            "      return str.length();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackIntStream {",
            "    @BeforeTemplate",
            "    long before(java.util.stream.IntStream a) {",
            "      return a.count();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackLongStream {",
            "    @BeforeTemplate",
            "    long before(java.util.stream.LongStream a) {",
            "      return a.count();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackDoubleStream {",
            "    @BeforeTemplate",
            "    long before(java.util.stream.DoubleStream a) {",
            "      return a.count();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackSequencedCollection {",
            "    @BeforeTemplate",
            "    int before(java.util.SequencedCollection<String> a) {",
            "      return a.size();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackPublisherProbe {",
            "    @BeforeTemplate",
            "    int before(PublisherProbe<String> a) {",
            "      return 0;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackAsyncCache {",
            "    @BeforeTemplate",
            "    int before(AsyncCache<String, String> a) {",
            "      return 0;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackAsyncLoadingCache {",
            "    @BeforeTemplate",
            "    int before(AsyncLoadingCache<String, String> a) {",
            "      return 0;",
            "    }",
            "  }",
            "",
            "  class UnaryWrap {",
            "    @BeforeTemplate",
            "    void before(boolean a) {",
            "      takeExpression(!a);",
            "    }",
            "  }",
            "",
            "  class BinaryWrapWithConstant {",
            "    @BeforeTemplate",
            "    void before(String str, int a) {",
            "      takeFromIndex(str, a - 1);",
            "    }",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import com.google.common.collect.ImmutableList;",
            "import com.google.errorprone.refaster.Refaster;",
            "import com.google.errorprone.refaster.annotation.AfterTemplate;",
            "import com.google.errorprone.refaster.annotation.BeforeTemplate;",
            "import com.google.errorprone.refaster.annotation.Matches;",
            "import com.google.errorprone.refaster.annotation.Repeated;",
            "import java.util.Comparator;",
            "import java.util.List;",
            "import java.util.OptionalInt;",
            "import java.util.function.Function;",
            "import tech.picnic.errorprone.refaster.matchers.IsEmpty;",
            "import tech.picnic.errorprone.refaster.matchers.IsIdentityOperation;",
            "",
            "class A {",
            "  static void helper(String value, int count) {}",
            "",
            "  static void helperStr(String str1) {}",
            "",
            "  static String other(String text) {",
            "    return text;",
            "  }",
            "",
            "  static String format(String format, Object... args) {",
            "    return format;",
            "  }",
            "",
            "  interface AsyncCache<K, V> {}",
            "",
            "  interface AsyncLoadingCache<K, V> {}",
            "",
            "  interface PublisherProbe<T> {}",
            "",
            "  static void takeExpression(boolean expression) {}",
            "",
            "  static void takeFromIndex(String str, int fromIndex) {}",
            "",
            "  class SimpleRename {",
            "    @BeforeTemplate",
            "    void before(String value) {",
            "      helper(value, 1);",
            "    }",
            "  }",
            "",
            "  class MultipleParameters {",
            "    @BeforeTemplate",
            "    void before(String value, int count) {",
            "      helper(value, count);",
            "    }",
            "  }",
            "",
            "  class AfterTemplateTakesPriority {",
            "    @BeforeTemplate",
            "    void before(String text) {",
            "      helper(text, 1);",
            "    }",
            "",
            "    @AfterTemplate",
            "    void after(String text) {",
            "      other(text);",
            "    }",
            "  }",
            "",
            "  class MixedRenameAndTypeFallback {",
            "    @BeforeTemplate",
            "    String before(String value, String str) {",
            "      helper(value, 1);",
            "      return str;",
            "    }",
            "  }",
            "",
            "  class FirstInvocationWins {",
            "    @BeforeTemplate",
            "    void before(String value) {",
            "      helper(value, 1);",
            "      other(value);",
            "    }",
            "  }",
            "",
            "  class NestedInvocation {",
            "    @BeforeTemplate",
            "    void before(String text, int count) {",
            "      helper(other(text), count);",
            "    }",
            "  }",
            "",
            "  class HigherArityBreaksTie {",
            "    @BeforeTemplate",
            "    void before1(String text) {",
            "      helper(text, 1);",
            "    }",
            "",
            "    @BeforeTemplate",
            "    void before2(String text, int i) {",
            "      other(text);",
            "    }",
            "  }",
            "",
            "  class ConflictResolutionWithSuffix {",
            "    @BeforeTemplate",
            "    void before(String value1, String value2) {",
            "      helper(value1, 1);",
            "      helper(value2, 1);",
            "    }",
            "  }",
            "",
            "  class SwapRename {",
            "    @BeforeTemplate",
            "    void before(String value, String text) {",
            "      helper(value, 1);",
            "      other(text);",
            "    }",
            "  }",
            "",
            "  class RepeatedParameterViaAsVarargs {",
            "    @BeforeTemplate",
            "    String before(String format, @Repeated Object args) {",
            "      return A.format(format, Refaster.asVarargs(args));",
            "    }",
            "  }",
            "",
            "  class TypeFallbackString {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return str;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackImmutableList {",
            "    @BeforeTemplate",
            "    int before(ImmutableList<String> list) {",
            "      return list.size();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackArray {",
            "    @BeforeTemplate",
            "    int before(String[] array) {",
            "      return array.length;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackComparator {",
            "    @BeforeTemplate",
            "    int before(Comparator<String> cmp) {",
            "      return cmp.compare(\"x\", \"y\");",
            "    }",
            "  }",
            "",
            "  class TypeFallbackStringBuilder {",
            "    @BeforeTemplate",
            "    String before(StringBuilder sb) {",
            "      return sb.toString();",
            "    }",
            "  }",
            "",
            "  class TypeConflict {",
            "    @BeforeTemplate",
            "    String before(String str1, String str2) {",
            "      return str1 + str2;",
            "    }",
            "  }",
            "",
            "  class MixedInvocationAndTypeFallback {",
            "    @BeforeTemplate",
            "    String before(String value, String str) {",
            "      helper(value, 1);",
            "      return str;",
            "    }",
            "  }",
            "",
            "  class PrimitiveFallback {",
            "    @BeforeTemplate",
            "    int before(int i) {",
            "      return i;",
            "    }",
            "  }",
            "",
            "  class KeywordFallbackMultiPart {",
            "    @BeforeTemplate",
            "    int before(OptionalInt optionalInt) {",
            "      return optionalInt.getAsInt();",
            "    }",
            "  }",
            "",
            "  class NonRepeatedAtVarargsPosition {",
            "    @BeforeTemplate",
            "    String before(String str) {",
            "      return A.format(\"%s\", str);",
            "    }",
            "  }",
            "",
            "  class CorrectlyNamedParamWithConflict {",
            "    @BeforeTemplate",
            "    void before(String value, String value1) {",
            "      helper(value, 1);",
            "      helper(value1, 1);",
            "    }",
            "  }",
            "",
            "  class OneParamAlreadyCorrect {",
            "    @BeforeTemplate",
            "    void before(String text, String value) {",
            "      other(text);",
            "      helper(value, 1);",
            "    }",
            "  }",
            "",
            "  class ConflictWithOccupiedSuffix<E> {",
            "    @BeforeTemplate",
            "    void before(E value1, String value2, String value3) {",
            "      helper(value2, 2);",
            "      helper(value3, 3);",
            "    }",
            "  }",
            "",
            "  class ArrayDimensionNaming {",
            "    @BeforeTemplate",
            "    String[] before(int size) {",
            "      return new String[size];",
            "    }",
            "  }",
            "",
            "  class IfConditionNaming {",
            "    @BeforeTemplate",
            "    void before(boolean condition) {",
            "      if (condition) {}",
            "    }",
            "  }",
            "",
            "  class NegatedIfConditionNaming {",
            "    @BeforeTemplate",
            "    void before(boolean condition) {",
            "      if (!condition) {}",
            "    }",
            "  }",
            "",
            "  class MatchesIsIdentityFunction {",
            "    @BeforeTemplate",
            "    <T, R> Function<T, R> before(",
            "        @Matches(IsIdentityOperation.class) Function<T, R> identityFunction) {",
            "      return identityFunction;",
            "    }",
            "  }",
            "",
            "  class MatchesIsEmptyList {",
            "    @BeforeTemplate",
            "    int before(@Matches(IsEmpty.class) List<String> emptyList) {",
            "      return emptyList.size();",
            "    }",
            "  }",
            "",
            "  class SuffixFamilyBool {",
            "    @BeforeTemplate",
            "    boolean before(Boolean b1, boolean b2) {",
            "      return b2;",
            "    }",
            "  }",
            "",
            "  class SuffixFamilyStr {",
            "    @BeforeTemplate",
            "    int before(String str1, String str2) {",
            "      helperStr(str1);",
            "      return str2.length();",
            "    }",
            "  }",
            "",
            "  class FixedNameInNumberedFamilyBool {",
            "    @BeforeTemplate",
            "    boolean before(boolean b1, boolean b2) {",
            "      return b2;",
            "    }",
            "  }",
            "",
            "  class FixedNameInNumberedFamilyStr {",
            "    @BeforeTemplate",
            "    int before(String str1, String str2) {",
            "      return str2.length();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackIntStream {",
            "    @BeforeTemplate",
            "    long before(java.util.stream.IntStream stream) {",
            "      return stream.count();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackLongStream {",
            "    @BeforeTemplate",
            "    long before(java.util.stream.LongStream stream) {",
            "      return stream.count();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackDoubleStream {",
            "    @BeforeTemplate",
            "    long before(java.util.stream.DoubleStream stream) {",
            "      return stream.count();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackSequencedCollection {",
            "    @BeforeTemplate",
            "    int before(java.util.SequencedCollection<String> collection) {",
            "      return collection.size();",
            "    }",
            "  }",
            "",
            "  class TypeFallbackPublisherProbe {",
            "    @BeforeTemplate",
            "    int before(PublisherProbe<String> probe) {",
            "      return 0;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackAsyncCache {",
            "    @BeforeTemplate",
            "    int before(AsyncCache<String, String> cache) {",
            "      return 0;",
            "    }",
            "  }",
            "",
            "  class TypeFallbackAsyncLoadingCache {",
            "    @BeforeTemplate",
            "    int before(AsyncLoadingCache<String, String> cache) {",
            "      return 0;",
            "    }",
            "  }",
            "",
            "  class UnaryWrap {",
            "    @BeforeTemplate",
            "    void before(boolean expression) {",
            "      takeExpression(!expression);",
            "    }",
            "  }",
            "",
            "  class BinaryWrapWithConstant {",
            "    @BeforeTemplate",
            "    void before(String str, int fromIndex) {",
            "      takeFromIndex(str, fromIndex - 1);",
            "    }",
            "  }",
            "}")
        .doTest();
  }
}
