changelog:
  exclude:
    labels:
      - ignore-changelog
  categories:
    - title: ":rocket: New Error Prone checks"
      labels:
        - "error prone check"
    - title: ":sunny: New Refaster templates"
      labels:
        - "refaster template"
    - title: ":sparkles: New features and improvements"
      labels:
        - "new feature"
        - improvement
    - title: ":warning: Update considerations and deprecations"
      labels:
        - "breaking change"
        - deprecation
    - title: ":bug: Bug fixes"
      labels:
        - bug
    - title: ":books: Documentation, tests and build"
      labels:
        - documentation
        - chores
    - title: ":chart_with_upwards_trend: Dependency upgrades"
      labels:
        - dependencies
    - title: "Other changes"
      labels:
        - "*"
