package tech.picnic.errorprone.documentation;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.BugPattern.SeverityLevel;
import java.net.URI;
import org.intellij.lang.annotations.Language;
import tech.picnic.errorprone.documentation.ProjectInfo.BugPatternInfo;
import tech.picnic.errorprone.documentation.ProjectInfo.BugPatternTestCases;
import tech.picnic.errorprone.documentation.ProjectInfo.BugPatternTestCases.TestEntry.Identification;
import tech.picnic.errorprone.documentation.ProjectInfo.BugPatternTestCases.TestEntry.Replacement;
import tech.picnic.errorprone.documentation.ProjectInfo.RefasterRuleCollection;
import tech.picnic.errorprone.documentation.ProjectInfo.RefasterTestCases;

/**
 * Project information data types that describe some aspect of the Error Prone Support project.
 *
 * <p>The data is mined from the project by {@link Extractor}s, persisted as JSON by the {@link
 * DocumentationGenerator} and later converted to Jekyll-consumable YAML files by the {@link
 * JekyllCollectionGenerator}. The website is then generated by Jekyll.
 */
// XXX: Drop the `@JsonSubTypes` annotation if/when
// https://github.com/FasterXML/jackson-databind/issues/3281 is resolved.
@JsonSubTypes({
  @JsonSubTypes.Type(BugPatternInfo.class),
  @JsonSubTypes.Type(BugPatternTestCases.class),
  @JsonSubTypes.Type(RefasterRuleCollection.class),
  @JsonSubTypes.Type(RefasterTestCases.class)
})
@JsonTypeInfo(use = JsonTypeInfo.Id.DEDUCTION)
sealed interface ProjectInfo {
  URI source();

  record BugPatternInfo(
      URI source,
      String fullyQualifiedName,
      String name,
      ImmutableList<String> altNames,
      String link,
      ImmutableList<String> tags,
      String summary,
      String explanation,
      SeverityLevel severityLevel,
      boolean canDisable,
      ImmutableList<String> suppressionAnnotations)
      implements ProjectInfo {}

  record BugPatternTestCases(
      URI source, String testClass, ImmutableList<BugPatternTestCase> testCases)
      implements ProjectInfo {
    record BugPatternTestCase(String classUnderTest, ImmutableList<TestEntry> entries) {}

    // XXX: Drop the `@JsonSubTypes` annotation if/when
    // https://github.com/FasterXML/jackson-databind/issues/3281 is resolved.
    @JsonSubTypes({@JsonSubTypes.Type(Identification.class), @JsonSubTypes.Type(Replacement.class)})
    @JsonTypeInfo(use = JsonTypeInfo.Id.DEDUCTION)
    sealed interface TestEntry {
      String path();

      record Identification(String path, @Language("java") String code) implements TestEntry {}

      record Replacement(
          String path, @Language("java") String input, @Language("java") String output)
          implements TestEntry {}
    }
  }

  // XXX: For this type there is no extractor yet; implement it.
  record RefasterRuleCollection(
      URI source, String name, String description, String link, ImmutableList<Rule> rules) {
    record Rule(String name, String description, String link, SeverityLevel severityLevel) {}
  }

  record RefasterTestCases(
      URI source, String ruleCollection, boolean isInput, ImmutableList<RefasterTestCase> testCases)
      implements ProjectInfo {
    record RefasterTestCase(String name, @Language("java") String content) {}
  }
}
