package tech.picnic.errorprone.documentation;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.google.common.collect.ImmutableList;
import com.google.errorprone.BugPattern.SeverityLevel;
import java.net.URI;
import org.intellij.lang.annotations.Language;

/**
 * Project information data types that describe some aspect of the Error Prone Support project.
 *
 * <p>The data is mined from the project by {@link Extractor}s, persisted as JSON by the {@link
 * DocumentationGenerator} and later converted to Jekyll-consumable YAML files by the {@link
 * JekyllCollectionGenerator}. The website is then generated by Jekyll.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.DEDUCTION)
sealed interface ProjectInfo {
  URI source();

  record BugPatternInfo(
      URI source,
      String fullyQualifiedName,
      String name,
      ImmutableList<String> altNames,
      String link,
      ImmutableList<String> tags,
      String summary,
      String explanation,
      SeverityLevel severityLevel,
      boolean canDisable,
      ImmutableList<String> suppressionAnnotations)
      implements ProjectInfo {}

  record BugPatternTestCases(
      URI source, String testClass, ImmutableList<BugPatternTestCase> testCases)
      implements ProjectInfo {
    record BugPatternTestCase(String classUnderTest, ImmutableList<TestEntry> entries) {}

    @JsonTypeInfo(use = JsonTypeInfo.Id.DEDUCTION)
    sealed interface TestEntry {
      String path();

      record Identification(String path, @Language("java") String code) implements TestEntry {}

      record Replacement(
          String path, @Language("java") String input, @Language("java") String output)
          implements TestEntry {}
    }
  }

  record RefasterRuleCollection(
      URI source, String name, String description, ImmutableList<Rule> rules)
      implements ProjectInfo {
    record Rule(String name, String description, SeverityLevel severityLevel) {}
  }

  record RefasterTestCases(
      URI source, String ruleCollection, boolean isInput, ImmutableList<RefasterTestCase> testCases)
      implements ProjectInfo {
    record RefasterTestCase(String name, @Language("java") String content) {}
  }
}
