package tech.picnic.errorprone.bugpatterns;

import com.google.errorprone.BugCheckerRefactoringTestHelper;
import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class BlockingPublisherCallbackTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(BlockingPublisherCallback.class, getClass())
        .addSourceLines(
            "A.java",
            "import java.util.List;",
            "import java.util.Optional;",
            "import java.util.concurrent.CompletableFuture;",
            "import java.util.concurrent.ExecutionException;",
            "import java.util.concurrent.Future;",
            "import java.util.function.Supplier;",
            "import java.util.stream.Stream;",
            "import reactor.core.publisher.Flux;",
            "import reactor.core.publisher.Mono;",
            "",
            "class A {",
            "  void m(CompletableFuture<Integer> completableFuture, Future<Integer> future) {",
            "    Flux.just(1).flatMap(i -> Mono.just(i));",
            "    Flux.just(2).map(i -> Flux.just(i).toIterable());",
            "",
            "    Mono.just(3).block();",
            "    Flux.just(4)",
            "        .map(",
            "            i ->",
            "                new Supplier<Integer>() {",
            "                  @Override",
            "                  public Integer get() {",
            "                    return Mono.just(i).block();",
            "                  }",
            "                });",
            "    Flux.just(5)",
            "        .map(",
            "            i ->",
            "                new Object() {",
            "                  final Integer value = Mono.just(i).block();",
            "                });",
            "    Flux.just(6).map(i -> (Supplier<Integer>) () -> Mono.just(i).block());",
            "",
            "    Mono.fromCallable(() -> Mono.just(7).block());",
            "    Flux.create(sink -> sink.next(Mono.just(8).block()));",
            "    Flux.just(9).flatMap(i -> Mono.fromSupplier(() -> Mono.just(i).block()));",
            "",
            "    Stream.of(10).map(i -> Mono.just(i).block());",
            "    Flux.just(11).as(f -> f.blockFirst());",
            "",
            "    CompletableFuture.runAsync(() -> Mono.just(12).block());",
            "    Flux.just(13).map(i -> CompletableFuture.runAsync(() -> Mono.just(i).block()));",
            "",
            "    // BUG: Diagnostic contains:",
            "    Mono.just(14).map(i -> Mono.just(i).block());",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(15).filter(i -> Mono.just(true).blockOptional().orElse(false));",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(16).flatMap(i -> Mono.justOrEmpty(Flux.just(i).blockFirst()));",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(17).concatMap(i -> Mono.justOrEmpty(Flux.just(i).blockLast()));",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(18).doOnNext(i -> completableFuture.join());",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(19).subscribe(i -> Mono.just(i).block());",
            "    // BUG: Diagnostic contains:",
            "    Mono.defer(() -> Mono.justOrEmpty(Mono.just(20).block()));",
            "    // BUG: Diagnostic contains:",
            "    Flux.zip(Flux.just(21), Flux.just(22), (a, b) -> Mono.just(a + b).block());",
            "",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(23).map(i -> Stream.of(i).map(j -> Mono.just(j).block()).count());",
            "    // BUG: Diagnostic contains:",
            "    Mono.just(24).map(i -> Optional.of(i).map(j -> Mono.just(j).block()));",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(List.of(25)).doOnNext(l -> l.forEach(i -> Mono.just(i).block()));",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(26).map(i -> Flux.just(i).as(f -> f.blockFirst()));",
            "",
            "    Flux.just(27)",
            "        .doOnNext(",
            "            i -> {",
            "              try {",
            "                // BUG: Diagnostic contains:",
            "                Thread.sleep(i);",
            "              } catch (InterruptedException e) {",
            "                Thread.currentThread().interrupt();",
            "              }",
            "            });",
            "",
            "    Mono.just(28)",
            "        .handle(",
            "            (i, sink) -> {",
            "              try {",
            "                // BUG: Diagnostic contains:",
            "                sink.next(future.get());",
            "              } catch (InterruptedException | ExecutionException e) {",
            "                sink.error(e);",
            "              }",
            "            });",
            "  }",
            "}")
        .doTest();
  }

  @Test
  void replacement() {
    BugCheckerRefactoringTestHelper.newInstance(BlockingPublisherCallback.class, getClass())
        .addInputLines(
            "A.java",
            "import java.time.Duration;",
            "import java.util.Optional;",
            "import reactor.core.publisher.Flux;",
            "import reactor.core.publisher.Mono;",
            "",
            "class A {",
            "  void m() {",
            "    Mono.just(1).map(i -> Mono.just(i).block() + 2);",
            "    Mono.just(3).map(i -> Optional.of(i).map(j -> Mono.just(j).block()));",
            "    Mono.just(4).map(i -> Mono.just(i).blockOptional());",
            "    Mono.just(5).map(i -> Mono.just(i).block(Duration.ZERO));",
            "    Mono.just(6).filter(i -> Mono.just(true).block());",
            "",
            "    Mono.just(7).map(i -> Mono.just(i + 8).block());",
            "    Flux.just(9).map(i -> Mono.just(i + 10).block());",
            "  }",
            "}")
        .addOutputLines(
            "A.java",
            "import java.time.Duration;",
            "import java.util.Optional;",
            "import reactor.core.publisher.Flux;",
            "import reactor.core.publisher.Mono;",
            "",
            "class A {",
            "  void m() {",
            "    Mono.just(1).map(i -> Mono.just(i).block() + 2);",
            "    Mono.just(3).map(i -> Optional.of(i).map(j -> Mono.just(j).block()));",
            "    Mono.just(4).map(i -> Mono.just(i).blockOptional());",
            "    Mono.just(5).map(i -> Mono.just(i).block(Duration.ZERO));",
            "    Mono.just(6).filter(i -> Mono.just(true).block());",
            "",
            "    Mono.just(7).flatMap(i -> Mono.just(i + 8));",
            "    Flux.just(9).concatMap(i -> Mono.just(i + 10));",
            "  }",
            "}")
        .doTest();
  }
}
