package tech.picnic.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class EnumValueOfUsageTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(EnumValueOfUsage.class, getClass())
        .addSourceLines(
            "Test.java",
            "class Test {",
            "  void unsafeCases(String raw, B b) {",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(\"FOUR\");",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(A.class, \"FOUR\");",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(raw);",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(A.class, raw);",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(b.name());",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(A.class, b.name());",
            "    var name =",
            "        switch (b) {",
            "          // BUG: Diagnostic contains:",
            "          case FOUR -> A.valueOf(b.name());",
            "          // BUG: Diagnostic contains:",
            "          case FIVE -> A.valueOf(A.class, b.name());",
            "          default -> null;",
            "        };",
            "    var toString =",
            "        switch (b) {",
            "          // BUG: Diagnostic contains:",
            "          case FOUR -> A.valueOf(b.toString());",
            "          // BUG: Diagnostic contains:",
            "          case FIVE -> A.valueOf(A.class, b.toString());",
            "          default -> null;",
            "        };",
            "    var defaultCase =",
            "        switch (b) {",
            "          case ONE -> null;",
            "          case FOUR -> null;",
            "          // BUG: Diagnostic contains:",
            "          default -> A.valueOf(b.name());",
            "        };",
            "  }",
            "",
            "  void safeCases(B b) {",
            "    A.valueOf(\"ONE\");",
            "    A.valueOf(A.class, \"TWO\");",
            "    var a =",
            "        switch (b) {",
            "          case ONE, THREE -> A.valueOf(A.class, b.name());",
            "          case TWO -> A.valueOf(b.name());",
            "          case FOUR -> A.valueOf(A.ONE.name());",
            "          default -> null;",
            "        };",
            "    var defaultCase =",
            "        switch (b) {",
            "          case FOUR, FIVE -> null;",
            "          default -> A.valueOf(b.name());",
            "        };",
            "  }",
            "",
            "  void ignoredCases() {",
            "    A.valueOf(rawMethod());",
            "    A.valueOf(A.class, rawMethod());",
            "    java.util.List.of(\"ONE\").stream().map(A::valueOf);",
            "  }",
            "",
            "  String rawMethod() {",
            "    return \"ONE\";",
            "  }",
            "",
            "  enum A {",
            "    ONE,",
            "    TWO,",
            "    THREE",
            "  }",
            "",
            "  enum B {",
            "    ONE,",
            "    TWO,",
            "    THREE,",
            "    FOUR,",
            "    FIVE",
            "  }",
            "}")
        .doTest();
  }
}
