package tech.picnic.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class FluxGroupByUsageTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(FluxGroupByUsage.class, getClass())
        .addSourceLines(
            "A.java",
            "import java.util.function.BiFunction;",
            "import java.util.function.Function;",
            "import reactor.core.CoreSubscriber;",
            "import reactor.core.publisher.Flux;",
            "import reactor.core.publisher.GroupedFlux;",
            "",
            "class A {",
            "  void m() {",
            "    new NonFlux().groupBy(Object::toString);",
            "    new FluxSubtype().groupBy();",
            "    Flux.just(1).groupBy(A::isEven);",
            "    Flux.just(2).groupBy(i -> Key.ONE);",
            "    Flux.just(3).groupBy(i -> Key.ONE, Object::toString);",
            "    Flux.just(4).groupBy(new EnumMapper());",
            "    Function<Integer, ? extends Key> wildcardMapper = i -> Key.ONE;",
            "    Flux.just(5).groupBy(wildcardMapper);",
            "    sinkEnum(Flux::groupBy);",
            "    Function<Function<Integer, Key>, Object> boundEnumGrouper = Flux.just(6)::groupBy;",
            "",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(7).groupBy(Object::toString);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(8).groupBy(Object::toString, 1);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(9).groupBy(Object::toString, Object::toString);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(10).groupBy(Object::toString, Object::toString, 1);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(11).groupBy(null);",
            "    // BUG: Diagnostic contains:",
            "    new FluxSubtype().groupBy(Object::toString);",
            "    // BUG: Diagnostic contains:",
            "    this.<Integer, Flux<GroupedFlux<Integer, Integer>>>sink(Flux::groupBy);",
            "  }",
            "",
            "  <E extends Enum<E>> void genericEnum(Function<Integer, E> mapper) {",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(12).groupBy(mapper);",
            "  }",
            "",
            "  private static boolean isEven(int value) {",
            "    return value % 2 == 0;",
            "  }",
            "",
            "  private <T, R> void sink(BiFunction<Flux<T>, Function<T, T>, R> function) {}",
            "",
            "  private void sinkEnum(",
            "      BiFunction<Flux<Integer>, Function<Integer, Key>, Flux<GroupedFlux<Key, Integer>>>",
            "          function) {}",
            "",
            "  private enum Key {",
            "    ONE",
            "  }",
            "",
            "  private static final class EnumMapper implements Function<Integer, Key> {",
            "    @Override",
            "    public Key apply(Integer value) {",
            "      return Key.ONE;",
            "    }",
            "  }",
            "",
            "  private static final class NonFlux {",
            "    void groupBy(Function<Integer, String> keyMapper) {}",
            "  }",
            "",
            "  private static final class FluxSubtype extends Flux<Integer> {",
            "    void groupBy() {}",
            "",
            "    @Override",
            "    public void subscribe(CoreSubscriber<? super Integer> subscriber) {}",
            "  }",
            "}")
        .doTest();
  }
}
