package tech.picnic.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class FluxGroupByUsageTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(FluxGroupByUsage.class, getClass())
        .addSourceLines(
            "A.java",
            "import java.io.Serializable;",
            "import java.util.function.BiFunction;",
            "import java.util.function.Consumer;",
            "import java.util.function.Function;",
            "import reactor.core.CoreSubscriber;",
            "import reactor.core.publisher.ConnectableFlux;",
            "import reactor.core.publisher.Flux;",
            "import reactor.core.publisher.GroupedFlux;",
            "",
            "class A {",
            "  @SuppressWarnings(\"FluxGroupByUsage\")",
            "  void suppressed() {",
            "    Flux.just(0).groupBy(Object::toString);",
            "  }",
            "",
            "  void m() {",
            "    new Grouper().groupBy();",
            "    this.<Grouper>sink(Grouper::groupBy);",
            "    new CustomFlux().groupBy();",
            "    new CustomFlux().groupBy(\"key\");",
            "    this.<CustomFlux>sink(CustomFlux::groupBy);",
            "    Flux.just(1).groupBy(A::isEven);",
            "    Flux.just(2).groupBy(A::isEven, 1);",
            "    Flux.just(3).groupBy(i -> Key.ONE);",
            "    Flux.just(4).groupBy(i -> Key.ONE, Object::toString);",
            "    Flux.just(5).groupBy(i -> Key.ONE, Object::toString, 1);",
            "    Function<Integer, Key> enumMapper = i -> Key.TWO;",
            "    Flux.just(6).groupBy(enumMapper);",
            "    sinkEnum(Flux::groupBy);",
            "    sinkEnumWidened(Flux::groupBy);",
            "    Function<Function<Integer, Key>, Object> boundEnumGrouper = Flux.just(6)::groupBy;",
            "    Flux.just(12).groupBy(new EnumMapper());",
            "    Flux.just(13)",
            "        .groupBy(",
            "            new Function<Integer, Key>() {",
            "              @Override",
            "              public Key apply(Integer value) {",
            "                return Key.ONE;",
            "              }",
            "            });",
            "    Flux.just(14).groupBy((Function<Integer, Key> & Serializable) (i -> Key.ONE));",
            "",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(7).groupBy(Object::toString);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(8).groupBy(Object::toString, 1);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(9).groupBy(Object::toString, Object::toString);",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(10).groupBy(Object::toString, Object::toString, 1);",
            "    // BUG: Diagnostic contains:",
            "    new CustomFlux().groupBy(Object::toString);",
            "",
            "    // BUG: Diagnostic contains:",
            "    this.<Integer, Flux<GroupedFlux<Integer, Integer>>>sink(Flux::groupBy);",
            "    BiFunction<Flux<Integer>, Function, Flux<GroupedFlux<Key, Integer>>>",
            "        // BUG: Diagnostic contains:",
            "        rawEnumGrouper = Flux::groupBy;",
            "  }",
            "",
            "  void wildcardKeys(",
            "      Flux<Integer> flux,",
            "      Function<Integer, ? extends Key> enumMapper,",
            "      Function<Integer, ? extends Boolean> booleanMapper) {",
            "    flux.groupBy(enumMapper);",
            "    flux.groupBy(booleanMapper);",
            "  }",
            "",
            "  void fluxSubtypes(ConnectableFlux<Integer> connectable, GroupedFlux<String, Integer> g) {",
            "    // BUG: Diagnostic contains:",
            "    connectable.groupBy(Object::toString);",
            "    // BUG: Diagnostic contains:",
            "    g.groupBy(Object::toString);",
            "  }",
            "",
            "  <E extends Enum<E>> void genericEnum(Function<Integer, E> mapper) {",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(11).groupBy(mapper);",
            "  }",
            "",
            "  void nullMapper() {",
            "    // BUG: Diagnostic contains:",
            "    Flux.just(15).groupBy(null);",
            "  }",
            "",
            "  private static boolean isEven(int value) {",
            "    return value % 2 == 0;",
            "  }",
            "",
            "  private <T, R> void sink(BiFunction<Flux<T>, Function<T, T>, R> function) {}",
            "",
            "  private <T> void sink(Consumer<T> consumer) {}",
            "",
            "  private void sinkEnum(",
            "      BiFunction<Flux<Integer>, Function<Integer, Key>, Flux<GroupedFlux<Key, Integer>>>",
            "          function) {}",
            "",
            "  private void sinkEnumWidened(",
            "      BiFunction<Flux<Integer>, Function<Integer, Key>, Object> function) {}",
            "",
            "  private enum Key {",
            "    ONE,",
            "    TWO",
            "  }",
            "",
            "  private static final class EnumMapper implements Function<Integer, Key> {",
            "    @Override",
            "    public Key apply(Integer value) {",
            "      return Key.ONE;",
            "    }",
            "  }",
            "",
            "  private static final class Grouper {",
            "    void groupBy() {}",
            "  }",
            "",
            "  private static final class CustomFlux extends Flux<Integer> {",
            "    void groupBy() {}",
            "",
            "    void groupBy(String key) {}",
            "",
            "    @Override",
            "    public void subscribe(CoreSubscriber<? super Integer> subscriber) {}",
            "  }",
            "}")
        .doTest();
  }
}
