package tech.picnic.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class UncheckedEnumValueOfInvocationTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(UncheckedEnumValueOfInvocation.class, getClass())
        .expectErrorMessage(
            "INVALID_TYPE",
            m -> m.contains("`<nulltype>` is not a valid type for `Foo.A`, expected: `String`"))
        .expectErrorMessage(
            "INVALID_VALUE",
            m -> m.contains("is not a valid value for `Foo.A`, possible values: [ONE, TWO, THREE]"))
        .expectErrorMessage(
            "MISSING_VALUE", m -> m.contains("might generate values which are missing in `Foo.A`"))
        .addSourceLines(
            "Foo.java",
            "import java.util.List;",
            "",
            "class Foo {",
            "  void safeCases(B b, C c) {",
            "    A validLabel1 = A.valueOf(\"ONE\");",
            "    A validLabel2 = A.valueOf(A.class, \"TWO\");",
            "    A hasAllLabels = A.valueOf(c.name());",
            "",
            "    A switchExpr =",
            "        switch (b) {",
            "          case ONE, THREE -> A.valueOf(A.class, b.name());",
            "          case TWO -> A.valueOf(b.name());",
            "          case FOUR -> A.valueOf(c.name());",
            "          default -> null;",
            "        };",
            "    A switchExprDefaultCase =",
            "        switch (b) {",
            "          case FOUR, FIVE -> null;",
            "          default -> A.valueOf(b.name());",
            "        };",
            "",
            "    switch (b) {",
            "      case ONE, THREE -> consume(A.valueOf(A.class, b.name()));",
            "      case TWO -> consume(A.valueOf(b.name()));",
            "      default -> {}",
            "    }",
            "    switch (b) {",
            "      case FOUR, FIVE -> {}",
            "      default -> consume(A.valueOf(b.name()));",
            "    }",
            "  }",
            "",
            "  void ignoredCases() {",
            "    A.valueOf(getClass().getSimpleName());",
            "    A.valueOf(A.class, getClass().getSimpleName());",
            "    List.of(\"\").stream().map(A::valueOf);",
            "  }",
            "",
            "  void unsafeCases(String raw, B b) {",
            "    // BUG: Diagnostic matches: INVALID_TYPE",
            "    A.valueOf(null);",
            "    // BUG: Diagnostic matches: INVALID_TYPE",
            "    A.valueOf(A.class, null);",
            "    // BUG: Diagnostic matches: INVALID_VALUE",
            "    A.valueOf(\"FOUR\");",
            "    // BUG: Diagnostic matches: INVALID_VALUE",
            "    A.valueOf(A.class, \"FOUR\");",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(raw);",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(A.class, raw);",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    A.valueOf(b.name());",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    A.valueOf(A.class, b.name());",
            "",
            "    A switchExprCaseLabel =",
            "        switch (b) {",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          case FOUR -> A.valueOf(b.name());",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          case FIVE -> A.valueOf(A.class, b.name());",
            "          default -> null;",
            "        };",
            "    A switchExprToString =",
            "        switch (b) {",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          case FOUR -> A.valueOf(b.toString());",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          case FIVE -> A.valueOf(A.class, b.toString());",
            "          default -> null;",
            "        };",
            "    A switchExprDefaultCase =",
            "        switch (b) {",
            "          case ONE, FOUR -> null;",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          default -> A.valueOf(b.name());",
            "        };",
            "",
            "    switch (b) {",
            "      // BUG: Diagnostic matches: MISSING_VALUE",
            "      case FOUR -> consume(A.valueOf(b.name()));",
            "      // BUG: Diagnostic matches: MISSING_VALUE",
            "      case FIVE -> consume(A.valueOf(A.class, b.name()));",
            "      default -> {}",
            "    }",
            "    switch (b) {",
            "      case ONE, FOUR -> {}",
            "      // BUG: Diagnostic matches: MISSING_VALUE",
            "      default -> consume(A.valueOf(b.name()));",
            "    }",
            "  }",
            "",
            "  private void consume(A a) {}",
            "",
            "  enum A {",
            "    ONE,",
            "    TWO,",
            "    THREE",
            "  }",
            "",
            "  enum B {",
            "    ONE,",
            "    TWO,",
            "    THREE,",
            "    FOUR,",
            "    FIVE",
            "  }",
            "",
            "  enum C {",
            "    ONE,",
            "    TWO",
            "  }",
            "}")
        .doTest();
  }
}
