package tech.picnic.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;
import org.junit.jupiter.api.Test;

final class UnvalidatedEnumValueOfInvocationTest {
  @Test
  void identification() {
    CompilationTestHelper.newInstance(UnvalidatedEnumValueOfInvocation.class, getClass())
        .expectErrorMessage(
            "INVALID_TYPE",
            m -> m.contains("`<nulltype>` is not a valid type for `Foo.A`, expected: `String`"))
        .expectErrorMessage(
            "INVALID_VALUE",
            m -> m.contains("is not a valid value for `Foo.A`, possible values: [ONE, TWO, THREE]"))
        .expectErrorMessage(
            "MISSING_VALUE", m -> m.contains("might generate values which are missing in `Foo.A`"))
        .addSourceLines(
            "Foo.java",
            "import java.util.List;",
            "",
            "class Foo {",
            "  void safeCases(B b, C c) {",
            "    A validLabel1 = A.valueOf(\"ONE\");",
            "    A validLabel2 = A.valueOf(A.class, \"TWO\");",
            "    A validLabel3 = Enum.valueOf(A.class, \"TWO\");",
            "    A hasAllLabels = A.valueOf(c.name());",
            "",
            "    A switchExpr =",
            "        switch (b) {",
            "          case ONE -> A.valueOf(A.class, b.name());",
            "          case THREE -> Enum.valueOf(A.class, b.name());",
            "          case TWO -> A.valueOf(b.name());",
            "          case FOUR -> A.valueOf(c.name());",
            "          default -> null;",
            "        };",
            "    A switchExprDefaultCase =",
            "        switch (b) {",
            "          case FOUR, FIVE -> null;",
            "          default -> {",
            "            A a1 = A.valueOf(b.name());",
            "            Enum.valueOf(A.class, b.name());",
            "            yield a1;",
            "          }",
            "        };",
            "",
            "    switch (b) {",
            "      case ONE -> consume(A.valueOf(A.class, b.name()));",
            "      case THREE -> consume(Enum.valueOf(A.class, b.name()));",
            "      case TWO -> consume(A.valueOf(b.name()));",
            "      default -> {}",
            "    }",
            "    switch (b) {",
            "      case FOUR, FIVE -> {}",
            "      default -> {",
            "        consume(A.valueOf(b.name()));",
            "        consume(Enum.valueOf(A.class, b.name()));",
            "      }",
            "    }",
            "    switch (b) {",
            "      case ONE, TWO, THREE, FOUR, FIVE -> {",
            "        consume(A.valueOf(B.ONE.name()));",
            "        consume(Enum.valueOf(A.class, B.TWO.name()));",
            "      }",
            "    }",
            "  }",
            "",
            "  void ignoredCases(B b) {",
            "    A.valueOf(getClass().getSimpleName());",
            "    A.valueOf(A.class, getClass().getSimpleName());",
            "    Enum.valueOf(A.class, getClass().getSimpleName());",
            "    A.valueOf(null, getClass().getSimpleName());",
            "    Enum.valueOf(null, getClass().getSimpleName());",
            "    List.of(\"\").stream().map(A::valueOf);",
            "",
            "    // Colon-style fall-through: `case FOUR` reaches the invocation, but only the",
            "    // enclosing `case ONE` label is analyzed (see XXX in the checker).",
            "    switch (b) {",
            "      case FOUR:",
            "      case ONE:",
            "        consume(A.valueOf(b.name()));",
            "        break;",
            "      default:",
            "    }",
            "  }",
            "",
            "  void unsafeCases(String raw, B b, D d) {",
            "    // BUG: Diagnostic matches: INVALID_TYPE",
            "    A.valueOf(null);",
            "    // BUG: Diagnostic matches: INVALID_TYPE",
            "    A.valueOf(A.class, null);",
            "    // BUG: Diagnostic matches: INVALID_TYPE",
            "    Enum.valueOf(A.class, null);",
            "    // BUG: Diagnostic matches: INVALID_VALUE",
            "    A.valueOf(\"FOUR\");",
            "    // BUG: Diagnostic matches: INVALID_VALUE",
            "    A.valueOf(A.class, \"FOUR\");",
            "    // BUG: Diagnostic matches: INVALID_VALUE",
            "    Enum.valueOf(A.class, \"FOUR\");",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(raw);",
            "    // BUG: Diagnostic contains:",
            "    A.valueOf(A.class, raw);",
            "    // BUG: Diagnostic contains:",
            "    Enum.valueOf(A.class, raw);",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    A.valueOf(b.name());",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    A.valueOf(A.class, b.name());",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    Enum.valueOf(A.class, b.name());",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    A.valueOf(b.toString());",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    A.valueOf(A.class, b.toString());",
            "    // BUG: Diagnostic matches: MISSING_VALUE",
            "    Enum.valueOf(A.class, b.toString());",
            "",
            "    A switchExprCaseLabel =",
            "        switch (b) {",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          case FOUR -> A.valueOf(b.name());",
            "          case FIVE -> {",
            "            // BUG: Diagnostic matches: MISSING_VALUE",
            "            A a1 = A.valueOf(A.class, b.name());",
            "            // BUG: Diagnostic matches: MISSING_VALUE",
            "            Enum.valueOf(A.class, b.name());",
            "            yield a1;",
            "          }",
            "          default -> null;",
            "        };",
            "    A switchExprToString =",
            "        switch (b) {",
            "          // BUG: Diagnostic matches: MISSING_VALUE",
            "          case FOUR -> A.valueOf(b.toString());",
            "          case FIVE -> {",
            "            // BUG: Diagnostic matches: MISSING_VALUE",
            "            A a1 = A.valueOf(A.class, b.toString());",
            "            // BUG: Diagnostic matches: MISSING_VALUE",
            "            Enum.valueOf(A.class, b.toString());",
            "            yield a1;",
            "          }",
            "          default -> null;",
            "        };",
            "    A switchExprDefaultCase =",
            "        switch (b) {",
            "          case ONE, FOUR -> null;",
            "          default -> {",
            "            // BUG: Diagnostic matches: MISSING_VALUE",
            "            A a1 = A.valueOf(b.name());",
            "            // BUG: Diagnostic matches: MISSING_VALUE",
            "            Enum.valueOf(A.class, b.name());",
            "            yield a1;",
            "          }",
            "        };",
            "",
            "    switch (b) {",
            "      // BUG: Diagnostic matches: MISSING_VALUE",
            "      case FOUR -> consume(A.valueOf(b.name()));",
            "      case FIVE -> {",
            "        // BUG: Diagnostic matches: MISSING_VALUE",
            "        consume(A.valueOf(A.class, b.name()));",
            "        // BUG: Diagnostic matches: MISSING_VALUE",
            "        consume(Enum.valueOf(A.class, b.name()));",
            "      }",
            "      default -> {}",
            "    }",
            "    switch (b) {",
            "      case ONE, FOUR -> {}",
            "      default -> {",
            "        // BUG: Diagnostic matches: MISSING_VALUE",
            "        consume(A.valueOf(b.name()));",
            "        // BUG: Diagnostic matches: MISSING_VALUE",
            "        consume(Enum.valueOf(A.class, b.name()));",
            "      }",
            "    }",
            "    switch (b) {",
            "      case ONE, TWO, THREE -> {",
            "        // BUG: Diagnostic matches: MISSING_VALUE",
            "        consume(A.valueOf(B.FOUR.name()));",
            "        // BUG: Diagnostic matches: MISSING_VALUE",
            "        consume(Enum.valueOf(A.class, B.FIVE.name()));",
            "      }",
            "      default -> {}",
            "    }",
            "",
            "    if (d instanceof D(B deconstructedB)) {",
            "      // BUG: Diagnostic matches: MISSING_VALUE",
            "      consume(A.valueOf(deconstructedB.name()));",
            "      // BUG: Diagnostic matches: MISSING_VALUE",
            "      consume(Enum.valueOf(A.class, deconstructedB.name()));",
            "    }",
            "  }",
            "",
            "  private void consume(A a) {}",
            "",
            "  enum A {",
            "    ONE,",
            "    TWO,",
            "    THREE",
            "  }",
            "",
            "  enum B {",
            "    ONE,",
            "    TWO,",
            "    THREE,",
            "    FOUR,",
            "    FIVE",
            "  }",
            "",
            "  enum C {",
            "    ONE,",
            "    TWO",
            "  }",
            "",
            "  record D(B b) {}",
            "}")
        .doTest();
  }
}
