package tech.picnic.errorprone.refasterrules;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import tech.picnic.errorprone.refaster.test.RefasterRuleCollection;

final class RefasterRulesTest {
  // XXX: Create a JUnit extension to automatically discover the rule collections in a given context
  // to make sure the list is exhaustive.
  @ParameterizedTest
  @ValueSource(
      classes = {
        AssertJArrayRules.class,
        AssertJBigDecimalRules.class,
        AssertJBigIntegerRules.class,
        AssertJBooleanRules.class,
        AssertJByteRules.class,
        AssertJCharSequenceRules.class,
        AssertJComparableRules.class,
        AssertJDoubleRules.class,
        AssertJDurationRules.class,
        AssertJEnumerableRules.class,
        AssertJFileRules.class,
        AssertJFloatRules.class,
        AssertJInstantRules.class,
        AssertJIntegerRules.class,
        AssertJIterableRules.class,
        AssertJIteratorRules.class,
        AssertJLongRules.class,
        AssertJMapRules.class,
        AssertJNumberRules.class,
        AssertJObjectRules.class,
        AssertJOptionalRules.class,
        AssertJPathRules.class,
        AssertJPrimitiveRules.class,
        AssertJRules.class,
        AssertJShortRules.class,
        AssertJStreamRules.class,
        AssertJStringRules.class,
        AssertJThrowingCallableRules.class,
        AssortedRules.class,
        BigDecimalRules.class,
        BugCheckerRules.class,
        CharSequenceRules.class,
        ClassRules.class,
        CollectionRules.class,
        ComparatorRules.class,
        DequeRules.class,
        DoubleStreamRules.class,
        EqualityRules.class,
        FileRules.class,
        ImmutableEnumSetRules.class,
        ImmutableListMultimapRules.class,
        ImmutableListRules.class,
        ImmutableMapRules.class,
        ImmutableMultisetRules.class,
        ImmutableSetMultimapRules.class,
        ImmutableSetRules.class,
        ImmutableSortedMapRules.class,
        ImmutableSortedMultisetRules.class,
        ImmutableSortedSetRules.class,
        ImmutableTableRules.class,
        InputStreamRules.class,
        IntStreamRules.class,
        Jackson2Rules.class,
        Jackson3Rules.class,
        JUnitRules.class,
        JUnitToAssertJRules.class,
        LongStreamRules.class,
        MapEntryRules.class,
        MapRules.class,
        MicrometerRules.class,
        MockitoRules.class,
        MultimapRules.class,
        NullRules.class,
        OptionalRules.class,
        PatternRules.class,
        PreconditionsRules.class,
        PrimitiveRules.class,
        RandomGeneratorRules.class,
        ReactorRules.class,
        RxJava2AdapterRules.class,
        SpringTestRules.class,
        StreamRules.class,
        StringBuilderRules.class,
        StringRules.class,
        SuggestedFixRules.class,
        TestNGToAssertJRules.class,
        TimeRules.class,
        WebClientRules.class
      })
  void validateRuleCollection(Class<?> clazz) {
    RefasterRuleCollection.validate(clazz);
  }
}
