package tech.picnic.errorprone.guidelines.bugpatterns;

import static com.google.errorprone.BugPattern.LinkType.CUSTOM;
import static com.google.errorprone.BugPattern.SeverityLevel.SUGGESTION;
import static com.google.errorprone.BugPattern.StandardTags.STYLE;
import static com.google.errorprone.matchers.ChildMultiMatcher.MatchType.AT_LEAST_ONE;
import static com.google.errorprone.matchers.Matchers.annotations;
import static com.google.errorprone.matchers.Matchers.hasAnnotation;
import static com.google.errorprone.matchers.Matchers.isType;
import static tech.picnic.errorprone.utils.Documentation.BUG_PATTERNS_BASE_URL;

import com.google.auto.service.AutoService;
import com.google.errorprone.BugPattern;
import com.google.errorprone.VisitorState;
import com.google.errorprone.bugpatterns.BugChecker;
import com.google.errorprone.bugpatterns.BugChecker.ClassTreeMatcher;
import com.google.errorprone.fixes.SuggestedFix;
import com.google.errorprone.fixes.SuggestedFixes;
import com.google.errorprone.matchers.Description;
import com.google.errorprone.matchers.Matcher;
import com.google.errorprone.matchers.MultiMatcher;
import com.google.errorprone.matchers.MultiMatcher.MultiMatchResult;
import com.google.errorprone.refaster.annotation.BeforeTemplate;
import com.google.errorprone.util.ASTHelpers;
import com.sun.source.tree.AnnotationTree;
import com.sun.source.tree.ClassTree;
import com.sun.source.tree.Tree;
import com.sun.tools.javac.code.Symbol;
import com.sun.tools.javac.code.Symbol.ClassSymbol;
import com.sun.tools.javac.code.Type;
import tech.picnic.errorprone.refaster.annotation.OpenRewriteIncompatible;
import tech.picnic.errorprone.utils.SourceCode;
import tech.picnic.errorprone.utils.ThirdPartyLibrary;

/**
 * A {@link BugChecker} that suggests that Refaster rules have the {@link OpenRewriteIncompatible}
 * annotation if and only if no OpenRewrite recipe is generated for them.
 *
 * <p>The {@code rewrite-templating} annotation processor silently omits Refaster rules that it
 * cannot express as an OpenRewrite recipe. This check surfaces such omissions at the rule
 * definition, so that the trade-off is visible when a rule is introduced or modified.
 *
 * <p>The check compares each Refaster rule against the recipe classes generated by the {@code
 * rewrite-templating} annotation processor, and must therefore run after those recipes have been
 * generated. Note that stale recipe classes from a prior build may cause omissions to go
 * unreported; results are authoritative only for builds performed from a clean state.
 */
// XXX: Document the presence of the associated annotation on the website; the documentation
// generation setup for Refaster rule annotations is still to be defined.
@AutoService(BugChecker.class)
@BugPattern(
    summary =
        "Refaster rules should be annotated with `@OpenRewriteIncompatible` if and only if no "
            + "OpenRewrite recipe is generated for them",
    link = BUG_PATTERNS_BASE_URL + "RefasterOpenRewriteCompatibility",
    linkType = CUSTOM,
    severity = SUGGESTION,
    tags = STYLE)
public final class RefasterOpenRewriteCompatibility extends BugChecker implements ClassTreeMatcher {
  private static final long serialVersionUID = 1L;
  private static final String OPEN_REWRITE_INCOMPATIBLE_ANNOTATION =
      "tech.picnic.errorprone.refaster.annotation.OpenRewriteIncompatible";

  private static final String RECIPE_COLLECTION_SUFFIX = "Recipes";
  private static final String RECIPE_SUFFIX = "Recipe";
  private static final Matcher<Tree> IS_BEFORE_TEMPLATE = hasAnnotation(BeforeTemplate.class);
  private static final MultiMatcher<Tree, AnnotationTree> HAS_OPEN_REWRITE_INCOMPATIBLE =
      annotations(AT_LEAST_ONE, isType(OPEN_REWRITE_INCOMPATIBLE_ANNOTATION));

  /** Instantiates a new {@link RefasterOpenRewriteCompatibility} instance. */
  public RefasterOpenRewriteCompatibility() {}

  @Override
  public Description matchClass(ClassTree tree, VisitorState state) {
    if (!ThirdPartyLibrary.OPEN_REWRITE_TEMPLATING.isIntroductionAllowed(state)) {
      /* Fast path: this project does not generate OpenRewrite recipes. */
      return Description.NO_MATCH;
    }

    if (tree.getMembers().stream().noneMatch(m -> IS_BEFORE_TEMPLATE.matches(m, state))) {
      /* Fast path: this is not a Refaster rule. */
      return dropAnnotationIfPresent(tree, state);
    }

    Symbol owner = ASTHelpers.getSymbol(tree).owner;
    if (!(owner instanceof ClassSymbol collection)) {
      /* Recipe generation is only understood for rules nested inside a rule collection. */
      return Description.NO_MATCH;
    }

    return hasGeneratedRecipe(tree, collection, state)
        ? dropAnnotationIfPresent(tree, state)
        : addAnnotationIfAbsent(tree, state);
  }

  /**
   * Tells whether the {@code rewrite-templating} annotation processor generated a recipe for the
   * given Refaster rule.
   */
  private static boolean hasGeneratedRecipe(
      ClassTree tree, ClassSymbol collection, VisitorState state) {
    Type recipes =
        state.getTypeFromString(collection.getQualifiedName() + RECIPE_COLLECTION_SUFFIX);
    if (recipes == null) {
      /* No recipe was generated for any rule in the enclosing rule collection. */
      return false;
    }

    String recipe = tree.getSimpleName() + RECIPE_SUFFIX;
    return ASTHelpers.getEnclosedElements(recipes.tsym).stream()
        .anyMatch(e -> e.getSimpleName().contentEquals(recipe));
  }

  private Description dropAnnotationIfPresent(ClassTree tree, VisitorState state) {
    MultiMatchResult<AnnotationTree> annotationMatch =
        HAS_OPEN_REWRITE_INCOMPATIBLE.multiMatchResult(tree, state);
    if (!annotationMatch.matches()) {
      return Description.NO_MATCH;
    }

    AnnotationTree annotation = annotationMatch.onlyMatchingNode();
    return describeMatch(annotation, SourceCode.deleteWithTrailingWhitespace(annotation, state));
  }

  private Description addAnnotationIfAbsent(ClassTree tree, VisitorState state) {
    if (HAS_OPEN_REWRITE_INCOMPATIBLE.matches(tree, state)) {
      return Description.NO_MATCH;
    }

    SuggestedFix.Builder fix = SuggestedFix.builder();
    String annotation =
        SuggestedFixes.qualifyType(state, fix, OPEN_REWRITE_INCOMPATIBLE_ANNOTATION);
    return describeMatch(tree, fix.prefixWith(tree, '@' + annotation + ' ').build());
  }
}
