ruby File.read(".ruby-version").strip

source "https://rubygems.org"

group :jekyll_site_dependencies do
  gem "jekyll", "4.3.2"
  gem "jekyll-sitemap", "1.4.0"
  gem "just-the-docs", "0.6.2"
  gem "rake", "13.0.6"
  gem "webrick", "1.8.1"
end

group :website_validation_dependencies do
  gem "html-proofer", "5.0.8"
end
