name: Build and verify Error Prone Support
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17 ]
    steps:
        # We run the build twice for each supported JDK: once against the
        # original Error Prone release, using only Error Prone checks available
        # on Maven Central, and once against the Picnic Error Prone fork,
        # additionally enabling all checks defined in this project and any
        # Error Prone checks available only from other artifact repositories.
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Display build environment details
        run: mvn --version
      - name: Build project against vanilla Error Prone
        run: mvn install --show-version -U
      - name: Build project with self-check against Error Prone fork
        run: mvn clean verify -Perror-prone-fork -Pnon-maven-central -Pself-check -s settings.xml

# XXX: Enable Codecov (`jacoco:prepare-agent surefire:test jacoco:report`) once we "go public".
# XXX: Enable SonarCloud once we "go public".
