# XXX: Once we've merged the remaining work on the `website` branch into
# `master`, merge the `deploy-website.yml` workflow into this file and deploy
# the website only if all builds pass. When doing this, also review which other
# workflow files can be combined. Also use that opportunity to revisit file
# names and workflow names.
# XXX: Let website deployment also depend on successful SNAPSHOT deployment.
# Then update the website to describe how users can use SNAPSHOTs.
name: Build and verify
on:
  pull_request:
  push:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  queue: ${{ github.event_name == 'pull_request' && 'single' || 'max' }}
permissions: {}
env:
  MAVEN_ARGS: --batch-mode -Dstyle.color=always -T1C
jobs:
  build:
    name: Build and verify project
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-15, windows-2025 ]
        build-jdk: [ 25.0.4 ]
        target-jdk: [ 21.0.12 ]
        include:
          - os: ubuntu-24.04
            build-jdk: 26.0.2
            target-jdk: 21.0.12
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Harden-Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          allowed-endpoints: >
            api.adoptium.net:443
            github.com:443
            github-registry-files.githubusercontent.com:443
            hosted-compute-watchdog-prod-*.githubapp.com:443
            maven.pkg.github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
      # We run the build twice for each supported JDK: once against the
      # original Error Prone release, using only Error Prone checks available
      # on Maven Central, and once against the Picnic Error Prone fork,
      # additionally enabling all checks defined in this project and any Error
      # Prone checks available only from other artifact repositories.
      - name: Check out code and set up JDK and Maven
        uses: s4u/setup-maven-action@4a02cbd99769e46198135c31d5097c94618ba3f5 # v1.21.0
        with:
          java-version: |
            ${{ matrix.target-jdk }}
            ${{ matrix.build-jdk }}
          java-distribution: temurin
          maven-version: 3.9.16
      - name: Build project against vanilla Error Prone, compile Javadoc
        run: mvn install javadoc:jar
      - name: Build project with self-check against Error Prone fork, test using the targeted JDK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # While generally we avoid expression interpolation inside `run`
        # arguments through the use of environment variables, we make an
        # exception here to avoid shell-conditional syntax: PowerShell expects
        # `$env:VAR` instead of `${VAR}`. We do not specify `shell: bash`, as
        # that would make the Windows test environment "less realistic", and
        # would cause e.g. some filesystem ACL settings to behave differently.
        # Note that `matrix.target-jdk` is controlled by this workflow, so this
        # compromise is safe.
        run: mvn clean verify -s settings.xml -Perror-prone-fork -Pself-check '-Dsurefire.jdk-toolchain-version=${{ matrix.target-jdk }}'
      - name: Remove installed project artifacts
        run: mvn dependency:purge-local-repository -DmanualInclude='${project.groupId}' -DresolutionFuzziness=groupId
  deploy:
    name: Deploy artifacts
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    needs: build
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    environment: maven-deploy
    steps:
      - name: Install Harden-Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          allowed-endpoints: >
            api.adoptium.net:443
            central.sonatype.com:443
            github.com:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
      - name: Check out code and set up JDK and Maven
        uses: s4u/setup-maven-action@4a02cbd99769e46198135c31d5097c94618ba3f5 # v1.21.0
        with:
          java-version: 25.0.4
          java-distribution: temurin
          maven-version: 3.9.16
      - name: Build and deploy
        env:
          MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_CENTRAL_PASS: ${{ secrets.MAVEN_CENTRAL_PASS }}
          MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
        run: mvn deploy -s settings.xml -DskipTests -Dverification.skip
