name: On-demand integration test
on:
  # run action every time a new comment is created
  issue_comment:
    types: [ created ]
permissions:
  contents: read
jobs:
  on_demand_integration_test:
    name: On-demand integration test
    # Only run the integration test if the created comment is on a pull request
    # and contains the string `/integration-test`
    if: | 
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/integration-test')
    # XXX TODO: Device matrix? 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1
        with:
          submodules: 'recursive'
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          # XXX TODO: java version matrix?
          java-version: 17.0.8
          distribution: temurin
          cache: maven
      - name: Display build environment details
        run: mvn --version
      - name: Install error-prone-support snapshot
        run: mvn -T1C install -DskipTests -Dverification.skip
      - name: Ensure runnable
        run: chmod +x ./integration-tests/run.sh
      - name: Check current directory
        run: pwd && ls -l
      - name: Run integration test
        run: ./integration-tests/run.sh
