# Runs integration tests against the project.
#
# The tests run in the following scenarios:
# - Any time code is pushed to the default branch.
# - When a user leaves a pull request comment containing the string
#   `/integration-test`.
#
# XXX: Review whether the build matrix should also vary JDK or OS versions.
# XXX: Have the integration test scripts select the JDK version to use, rather
# than having this workflow set the same `JAVA_HOME` override for all.
# XXX: Support `/integration-test [name...]` comment syntax to specify the
# subset of integration tests to run.
# See this example of a dynamic build matrix:
# https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
name: Integration tests
on:
  issue_comment:
    types: [ created ]
  push:
    branches: [ master ]
permissions:
  contents: read
env:
  MAVEN_ARGS: --batch-mode -Dstyle.color=always -T1C
jobs:
  acknowledge-request:
    name: Acknowledge request
    # Only run this job if it is a PR comment containing the command.
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/integration-test') }}
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    outputs:
      comment_id: ${{ steps.post-comment.outputs.commentId }}
    steps:
      - name: Post comment with workflow link
        id: post-comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;

            const response = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[Integration tests](${runUrl}) started. :rocket:`
            });

            core.setOutput('commentId', response.data.id);
  run-integration-tests:
    name: Integration test
    # On push events `acknowledge-request` is skipped; `always()` ensures this
    # job still runs in that case.
    needs: [ acknowledge-request ]
    if: ${{ always() && (!github.event.issue.pull_request || contains(github.event.comment.body, '/integration-test')) }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        integration-test:
          - checkstyle
          - metrics
          - prometheus-java-client
    steps:
      - name: Install Harden-Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          # We can't use `disable-sudo-and-containers` here, as some
          # integration test projects have unit tests that start Docker
          # containers.
          disable-sudo: true
          egress-policy: block
          # XXX: After updating the validation build flags in
          # `integration-tests/prometheus-java-client.sh`, review whether the
          # Docker domains specified here can be dropped.
          allowed-endpoints: >
            api.adoptium.net:443
            auth.docker.io:443
            checkstyle.org:443
            github.com:443
            hosted-compute-watchdog-prod-*.githubapp.com:443
            objects.githubusercontent.com:443
            oss.sonatype.org:443
            production.cloudflare.docker.com:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
            repository.sonatype.org:443
      - name: Check out code and set up JDK and Maven
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          checkout-ref: ${{ github.event.issue.pull_request && format('refs/pull/{0}/head', github.event.issue.number) || github.ref }}
          java-version: |
            21.0.10
            25.0.2
          java-distribution: temurin
          maven-version: 3.9.14
      - name: Install project to local Maven repository
        run: mvn install -DskipTests -Dverification.skip
      - name: Run integration test
        run: xvfb-run "./integration-tests/${{ matrix.integration-test }}.sh" "${{ runner.temp }}/artifacts"
        env:
          JAVA_HOME: "${{ env.JAVA_HOME_21_X64 }}"
      - name: Upload artifacts on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "integration-test-${{ matrix.integration-test }}"
          path: "${{ runner.temp }}/artifacts"
      - name: Remove installed project artifacts
        run: mvn dependency:purge-local-repository -DmanualInclude='${project.groupId}' -DresolutionFuzziness=groupId
  report-outcome:
    name: Report integration test result
    needs: [ acknowledge-request, run-integration-tests ]
    # Using `always()` ensures that this job runs even if previous jobs failed
    # or were cancelled.
    if: ${{ always() && github.event.issue.pull_request && needs.acknowledge-request.outputs.comment_id }}
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Update comment with results
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const conclusion = '${{ needs.run-integration-tests.result }}';

            let [statusEmoji, message] = (() => {
              switch (conclusion) {
                case 'success':
                  return [':white_check_mark:', 'Integration tests passed successfully!'];
                case 'cancelled':
                  return [':stop_sign:', 'The workflow was cancelled.'];
                default:
                  return [':x:', 'Integration tests failed. Please check the logs.'];
              }
            })();

            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ needs.acknowledge-request.outputs.comment_id }},
              body: `[Integration tests](${runUrl}) completed. ${statusEmoji} ${conclusion.toUpperCase()}: ${message}`
            });
