# Updates a pull request based on the corresponding mutation testing analysis
# performed by the `pitest-analyze-pr.yml` workflow. See
# https://blog.pitest.org/oss-pitest-pr/ for details.
name: Post mutation test results
on:
  workflow_run:
    workflows: ["Run mutation tests"]
    types: [ completed ]
permissions:
  contents: read
env:
  MAVEN_ARGS: --batch-mode -Dstyle.color=always -T1C
jobs:
  update-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Install Harden-Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo-and-containers: true
          allowed-endpoints: >
            api.adoptium.net:443
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
      - name: Check out code and set up JDK and Maven
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          java-version: 25.0.2
          java-distribution: temurin
          maven-version: 3.9.14
      - name: Download Pitest analysis artifact
        uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pitest-reports
          path: ./target/pit-reports-ci
      - name: Update PR
        run: mvn -DrepoToken="${{ secrets.GITHUB_TOKEN }}" pitest-github:updatePR
