name: Run Reviewdog
on:
  pull_request:
permissions:
  contents: read
jobs:
  analyze:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Install Harden-Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo-and-containers: true
          # XXX: Configure `allowed-endpoints` instead.
          egress-policy: audit
      - name: Check out code and set up JDK and Maven
        uses: s4u/setup-maven-action@4f7fb9d9675e899ca81c6161dadbba0189a4ebb1 # v1.18.0
        with:
          java-version: 17.0.13
          java-distribution: temurin
          maven-version: 3.9.9
      - name: Set up Reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          # XXX: Configure Renovate to maintain this version.
          reviewdog_version: v0.20.3
      - name: Install project to local Maven repository
        # XXX: Consider configuring Reviewdog such that it reports build
        # errors. When doing so, make sure that a nonzero `mvn` exit code does
        # abort this workflow.
        run: mvn -T1C install -DskipTests -Dverification.skip
      - name: Build project with self-check and report issues
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # XXX: Reorder flags?
        # XXX: Change `-name` flag?`
        # XXX: Run `mvn clean verify -DskipTests` instead, and also report
        # non-Error Prone issues.
        # XXX: Run `mvn clean test -Dmaven.test.failure.ignore` instead, and
        # also report Surefire test failures.
        run: |
          mvn -T1C clean test-compile -Perror-prone -Pself-check -Dverification.warn \
            | reviewdog \
                -name=javac \
                -efm='[WARNING] %f:[%l,%c] %m' \
                -filter-mode=file \
                -reporter=github-pr-review \
                -tee
      - name: Apply Error Prone suggestions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./apply-error-prone-suggestions.sh
      - name: Report suggested changes
        uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
        with:
          tool_name: Error Prone
      - name: Remove installed project artifacts
        run: mvn dependency:purge-local-repository -DmanualInclude='${project.groupId}' -DresolutionFuzziness=groupId
